package com.cbice.distribute.core.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSysUserExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public TSysUserExample(){
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public void setOrderByClause(String orderByClause){
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public String getOrderByClause(){
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public void setDistinct(boolean distinct){
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public boolean isDistinct(){
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public List<Criteria> getOredCriteria(){
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public void or(Criteria criteria){
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public Criteria or(){
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public Criteria createCriteria(){
        Criteria criteria = createCriteriaInternal();
        if(oredCriteria.size() == 0){
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    protected Criteria createCriteriaInternal(){
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public void clear(){
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    protected abstract static class GeneratedCriteria{
        protected List<Criterion> criteria;

        protected GeneratedCriteria(){
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid(){
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria(){
            return criteria;
        }

        public List<Criterion> getCriteria(){
            return criteria;
        }

        protected void addCriterion(String condition){
            if(condition == null){
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property){
            if(value == null){
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property){
            if(value1 == null || value2 == null){
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull(){
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull(){
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value){
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value){
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value){
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value){
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value){
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value){
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values){
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values){
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2){
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2){
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull(){
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull(){
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value){
            addCriterion("login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value){
            addCriterion("login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value){
            addCriterion("login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value){
            addCriterion("login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value){
            addCriterion("login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value){
            addCriterion("login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value){
            addCriterion("login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value){
            addCriterion("login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values){
            addCriterion("login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values){
            addCriterion("login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2){
            addCriterion("login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2){
            addCriterion("login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNull(){
            addCriterion("login_pwd is null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNotNull(){
            addCriterion("login_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdEqualTo(String value){
            addCriterion("login_pwd =", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotEqualTo(String value){
            addCriterion("login_pwd <>", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThan(String value){
            addCriterion("login_pwd >", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThanOrEqualTo(String value){
            addCriterion("login_pwd >=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThan(String value){
            addCriterion("login_pwd <", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThanOrEqualTo(String value){
            addCriterion("login_pwd <=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLike(String value){
            addCriterion("login_pwd like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotLike(String value){
            addCriterion("login_pwd not like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIn(List<String> values){
            addCriterion("login_pwd in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotIn(List<String> values){
            addCriterion("login_pwd not in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdBetween(String value1, String value2){
            addCriterion("login_pwd between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotBetween(String value1, String value2){
            addCriterion("login_pwd not between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull(){
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull(){
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value){
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value){
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value){
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value){
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value){
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value){
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value){
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value){
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values){
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values){
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2){
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2){
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull(){
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull(){
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value){
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value){
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value){
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value){
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value){
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value){
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value){
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value){
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values){
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values){
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2){
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2){
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull(){
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull(){
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value){
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value){
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value){
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value){
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value){
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value){
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value){
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value){
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values){
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values){
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2){
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2){
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdIsNull(){
            addCriterion("last_mod_sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdIsNotNull(){
            addCriterion("last_mod_sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdEqualTo(Long value){
            addCriterion("last_mod_sys_user_id =", value, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdNotEqualTo(Long value){
            addCriterion("last_mod_sys_user_id <>", value, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdGreaterThan(Long value){
            addCriterion("last_mod_sys_user_id >", value, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdGreaterThanOrEqualTo(Long value){
            addCriterion("last_mod_sys_user_id >=", value, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdLessThan(Long value){
            addCriterion("last_mod_sys_user_id <", value, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdLessThanOrEqualTo(Long value){
            addCriterion("last_mod_sys_user_id <=", value, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdIn(List<Long> values){
            addCriterion("last_mod_sys_user_id in", values, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdNotIn(List<Long> values){
            addCriterion("last_mod_sys_user_id not in", values, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdBetween(Long value1, Long value2){
            addCriterion("last_mod_sys_user_id between", value1, value2, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModSysUserIdNotBetween(Long value1, Long value2){
            addCriterion("last_mod_sys_user_id not between", value1, value2, "lastModSysUserId");
            return (Criteria) this;
        }

        public Criteria andLastModTsIsNull(){
            addCriterion("last_mod_ts is null");
            return (Criteria) this;
        }

        public Criteria andLastModTsIsNotNull(){
            addCriterion("last_mod_ts is not null");
            return (Criteria) this;
        }

        public Criteria andLastModTsEqualTo(Date value){
            addCriterion("last_mod_ts =", value, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsNotEqualTo(Date value){
            addCriterion("last_mod_ts <>", value, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsGreaterThan(Date value){
            addCriterion("last_mod_ts >", value, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsGreaterThanOrEqualTo(Date value){
            addCriterion("last_mod_ts >=", value, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsLessThan(Date value){
            addCriterion("last_mod_ts <", value, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsLessThanOrEqualTo(Date value){
            addCriterion("last_mod_ts <=", value, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsIn(List<Date> values){
            addCriterion("last_mod_ts in", values, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsNotIn(List<Date> values){
            addCriterion("last_mod_ts not in", values, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsBetween(Date value1, Date value2){
            addCriterion("last_mod_ts between", value1, value2, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andLastModTsNotBetween(Date value1, Date value2){
            addCriterion("last_mod_ts not between", value1, value2, "lastModTs");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull(){
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull(){
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value){
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value){
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value){
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value){
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value){
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value){
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values){
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values){
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2){
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2){
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_sys_user
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    public static class Criterion{
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition(){
            return condition;
        }

        public Object getValue(){
            return value;
        }

        public Object getSecondValue(){
            return secondValue;
        }

        public boolean isNoValue(){
            return noValue;
        }

        public boolean isSingleValue(){
            return singleValue;
        }

        public boolean isBetweenValue(){
            return betweenValue;
        }

        public boolean isListValue(){
            return listValue;
        }

        public String getTypeHandler(){
            return typeHandler;
        }

        protected Criterion(String condition){
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler){
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if(value instanceof List<?>){
                this.listValue = true;
            }else{
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value){
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler){
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue){
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_user
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 15 14:44:32 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}