package com.cbice.distribute.core.db.model;

import java.util.Date;

public class TGoodsBatch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.goods_num
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String goodsNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.goods_name
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String goodsName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.creat_time
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Date creatTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.states
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Integer states;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.t_user_id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Long tUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_batch.t_higer_user_id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Long tHigerUserId;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.id
	 * @return  the value of t_goods_batch.id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.id
	 * @param id  the value for t_goods_batch.id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.goods_num
	 * @return  the value of t_goods_batch.goods_num
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public String getGoodsNum() {
		return goodsNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.goods_num
	 * @param goodsNum  the value for t_goods_batch.goods_num
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void setGoodsNum(String goodsNum) {
		this.goodsNum = goodsNum == null ? null : goodsNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.goods_name
	 * @return  the value of t_goods_batch.goods_name
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.goods_name
	 * @param goodsName  the value for t_goods_batch.goods_name
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.creat_time
	 * @return  the value of t_goods_batch.creat_time
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public Date getCreatTime() {
		return creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.creat_time
	 * @param creatTime  the value for t_goods_batch.creat_time
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.states
	 * @return  the value of t_goods_batch.states
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public Integer getStates() {
		return states;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.states
	 * @param states  the value for t_goods_batch.states
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void setStates(Integer states) {
		this.states = states;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.t_user_id
	 * @return  the value of t_goods_batch.t_user_id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public Long gettUserId() {
		return tUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.t_user_id
	 * @param tUserId  the value for t_goods_batch.t_user_id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void settUserId(Long tUserId) {
		this.tUserId = tUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_batch.t_higer_user_id
	 * @return  the value of t_goods_batch.t_higer_user_id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public Long gettHigerUserId() {
		return tHigerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_batch.t_higer_user_id
	 * @param tHigerUserId  the value for t_goods_batch.t_higer_user_id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	public void settHigerUserId(Long tHigerUserId) {
		this.tHigerUserId = tHigerUserId;
	}

	private String showTime;

	public String getShowTime() {
		return showTime;
	}

	public void setShowTime(String showTime) {
		this.showTime = showTime;
	}

	
	/**
	 * 分页�?
	 */
	private int limit;
	
	private int start;

	public int getLimit() {
		return limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getStart() {
		return start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	
	private String agencyName;//经销商名称
	public String getAgencyName() {
		return agencyName;
	}

	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}
	
	
	
	
}