package com.cbice.distribute.core.db.data;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cbice.distribute.core.db.model.TSysBusiRole;
import com.cbice.distribute.core.db.model.TSysBusiRoleExample;

public interface TSysBusiRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int countByExample(TSysBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int deleteByExample(TSysBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int insert(TSysBusiRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int insertSelective(TSysBusiRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    List<TSysBusiRole> selectByExample(TSysBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    TSysBusiRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysBusiRole record, @Param("example") TSysBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int updateByExample(@Param("record") TSysBusiRole record, @Param("example") TSysBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int updateByPrimaryKeySelective(TSysBusiRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int updateByPrimaryKey(TSysBusiRole record);
    
    List<TSysBusiRole> selectByUserId(Long userId);
    
    int countByCondition(Map<String, Object> map);
    
    List<TSysBusiRole> selectByCondition(Map<String, Object> map);
}