package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TAgencyRole;
import com.cbice.distribute.core.db.model.TAgencyRoleExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAgencyRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int countByExample(TAgencyRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int deleteByExample(TAgencyRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int insert(TAgencyRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int insertSelective(TAgencyRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	List<TAgencyRole> selectByExample(TAgencyRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	TAgencyRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TAgencyRole record,
			@Param("example") TAgencyRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByExample(@Param("record") TAgencyRole record,
			@Param("example") TAgencyRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByPrimaryKeySelective(TAgencyRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByPrimaryKey(TAgencyRole record);
    
	List<TAgencyRole> selectByUserId(Long userId);
    
    List<TAgencyRole> selectByBusiRoleId(Long busiRoleId);
}