package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TAgencyBusiRoleRole;
import com.cbice.distribute.core.db.model.TAgencyBusiRoleRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAgencyBusiRoleRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int countByExample(TAgencyBusiRoleRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int deleteByExample(TAgencyBusiRoleRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int deleteByPrimaryKey(@Param("roleId") Long roleId,
			@Param("busiRoleId") Long busiRoleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int insert(TAgencyBusiRoleRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int insertSelective(TAgencyBusiRoleRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	List<TAgencyBusiRoleRole> selectByExample(TAgencyBusiRoleRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TAgencyBusiRoleRole record,
			@Param("example") TAgencyBusiRoleRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByExample(@Param("record") TAgencyBusiRoleRole record,
			@Param("example") TAgencyBusiRoleRoleExample example);
	
	int deleteByRoleId(long roleId);
}