package com.cbice.distribute.core.db.model;

public class HsCommodityRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.com_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long comId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.exchange_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long exchangeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.sys_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String sysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.com_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String comName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.exchange_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String exchangeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.exchange_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long exchangeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.com_type
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Integer comType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.backup1
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.backup2
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.backup3
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.backup4
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity_rule.backup5
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup5;



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.com_id
	 * @return  the value of hs_commodity_rule.com_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.com_id
	 * @param comId  the value for hs_commodity_rule.com_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setComId(Long comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.exchange_id
	 * @return  the value of hs_commodity_rule.exchange_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getExchangeId() {
		return exchangeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.exchange_id
	 * @param exchangeId  the value for hs_commodity_rule.exchange_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setExchangeId(Long exchangeId) {
		this.exchangeId = exchangeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.sys_id
	 * @return  the value of hs_commodity_rule.sys_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getSysId() {
		return sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.sys_id
	 * @param sysId  the value for hs_commodity_rule.sys_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId == null ? null : sysId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.com_name
	 * @return  the value of hs_commodity_rule.com_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getComName() {
		return comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.com_name
	 * @param comName  the value for hs_commodity_rule.com_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setComName(String comName) {
		this.comName = comName == null ? null : comName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.exchange_name
	 * @return  the value of hs_commodity_rule.exchange_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getExchangeName() {
		return exchangeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.exchange_name
	 * @param exchangeName  the value for hs_commodity_rule.exchange_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setExchangeName(String exchangeName) {
		this.exchangeName = exchangeName == null ? null : exchangeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.exchange_num
	 * @return  the value of hs_commodity_rule.exchange_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getExchangeNum() {
		return exchangeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.exchange_num
	 * @param exchangeNum  the value for hs_commodity_rule.exchange_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setExchangeNum(Long exchangeNum) {
		this.exchangeNum = exchangeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.com_type
	 * @return  the value of hs_commodity_rule.com_type
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Integer getComType() {
		return comType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.com_type
	 * @param comType  the value for hs_commodity_rule.com_type
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setComType(Integer comType) {
		this.comType = comType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.backup1
	 * @return  the value of hs_commodity_rule.backup1
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup1() {
		return backup1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.backup1
	 * @param backup1  the value for hs_commodity_rule.backup1
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup1(String backup1) {
		this.backup1 = backup1 == null ? null : backup1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.backup2
	 * @return  the value of hs_commodity_rule.backup2
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup2() {
		return backup2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.backup2
	 * @param backup2  the value for hs_commodity_rule.backup2
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup2(String backup2) {
		this.backup2 = backup2 == null ? null : backup2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.backup3
	 * @return  the value of hs_commodity_rule.backup3
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup3() {
		return backup3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.backup3
	 * @param backup3  the value for hs_commodity_rule.backup3
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup3(String backup3) {
		this.backup3 = backup3 == null ? null : backup3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.backup4
	 * @return  the value of hs_commodity_rule.backup4
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup4() {
		return backup4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.backup4
	 * @param backup4  the value for hs_commodity_rule.backup4
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup4(String backup4) {
		this.backup4 = backup4 == null ? null : backup4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity_rule.backup5
	 * @return  the value of hs_commodity_rule.backup5
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup5() {
		return backup5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity_rule.backup5
	 * @param backup5  the value for hs_commodity_rule.backup5
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup5(String backup5) {
		this.backup5 = backup5 == null ? null : backup5.trim();
	}

	private String saleUnit;
	private long freezeNum;
	private long currencyNum;
	private Integer minNum;
	
	

	public Integer getMinNum() {
		return minNum;
	}

	public void setMinNum(Integer minNum) {
		this.minNum = minNum;
	}

	public long getFreezeNum() {
		return freezeNum;
	}

	public void setFreezeNum(long freezeNum) {
		this.freezeNum = freezeNum;
	}

	public long getCurrencyNum() {
		return currencyNum;
	}

	public void setCurrencyNum(long currencyNum) {
		this.currencyNum = currencyNum;
	}

	public String getSaleUnit() {
		return saleUnit;
	}

	public void setSaleUnit(String saleUnit) {
		this.saleUnit = saleUnit;
	}
	
	
}