package com.cbice.distribute.core.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HsExchangeOrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public HsExchangeOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSysIdIsNull() {
			addCriterion("sys_id is null");
			return (Criteria) this;
		}

		public Criteria andSysIdIsNotNull() {
			addCriterion("sys_id is not null");
			return (Criteria) this;
		}

		public Criteria andSysIdEqualTo(String value) {
			addCriterion("sys_id =", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotEqualTo(String value) {
			addCriterion("sys_id <>", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdGreaterThan(String value) {
			addCriterion("sys_id >", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_id >=", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdLessThan(String value) {
			addCriterion("sys_id <", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdLessThanOrEqualTo(String value) {
			addCriterion("sys_id <=", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdLike(String value) {
			addCriterion("sys_id like", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotLike(String value) {
			addCriterion("sys_id not like", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdIn(List<String> values) {
			addCriterion("sys_id in", values, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotIn(List<String> values) {
			addCriterion("sys_id not in", values, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdBetween(String value1, String value2) {
			addCriterion("sys_id between", value1, value2, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotBetween(String value1, String value2) {
			addCriterion("sys_id not between", value1, value2, "sysId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("order_type is null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("order_type is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeEqualTo(Integer value) {
			addCriterion("order_type =", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotEqualTo(Integer value) {
			addCriterion("order_type <>", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThan(Integer value) {
			addCriterion("order_type >", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_type >=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThan(Integer value) {
			addCriterion("order_type <", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(Integer value) {
			addCriterion("order_type <=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIn(List<Integer> values) {
			addCriterion("order_type in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotIn(List<Integer> values) {
			addCriterion("order_type not in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeBetween(Integer value1, Integer value2) {
			addCriterion("order_type between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("order_type not between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdIsNull() {
			addCriterion("be_exchange_id is null");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdIsNotNull() {
			addCriterion("be_exchange_id is not null");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdEqualTo(Long value) {
			addCriterion("be_exchange_id =", value, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdNotEqualTo(Long value) {
			addCriterion("be_exchange_id <>", value, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdGreaterThan(Long value) {
			addCriterion("be_exchange_id >", value, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("be_exchange_id >=", value, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdLessThan(Long value) {
			addCriterion("be_exchange_id <", value, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdLessThanOrEqualTo(Long value) {
			addCriterion("be_exchange_id <=", value, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdIn(List<Long> values) {
			addCriterion("be_exchange_id in", values, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdNotIn(List<Long> values) {
			addCriterion("be_exchange_id not in", values, "beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdBetween(Long value1, Long value2) {
			addCriterion("be_exchange_id between", value1, value2,
					"beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeIdNotBetween(Long value1, Long value2) {
			addCriterion("be_exchange_id not between", value1, value2,
					"beExchangeId");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameIsNull() {
			addCriterion("be_exchange_name is null");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameIsNotNull() {
			addCriterion("be_exchange_name is not null");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameEqualTo(String value) {
			addCriterion("be_exchange_name =", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameNotEqualTo(String value) {
			addCriterion("be_exchange_name <>", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameGreaterThan(String value) {
			addCriterion("be_exchange_name >", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameGreaterThanOrEqualTo(String value) {
			addCriterion("be_exchange_name >=", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameLessThan(String value) {
			addCriterion("be_exchange_name <", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameLessThanOrEqualTo(String value) {
			addCriterion("be_exchange_name <=", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameLike(String value) {
			addCriterion("be_exchange_name like", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameNotLike(String value) {
			addCriterion("be_exchange_name not like", value, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameIn(List<String> values) {
			addCriterion("be_exchange_name in", values, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameNotIn(List<String> values) {
			addCriterion("be_exchange_name not in", values, "beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameBetween(String value1, String value2) {
			addCriterion("be_exchange_name between", value1, value2,
					"beExchangeName");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNameNotBetween(String value1, String value2) {
			addCriterion("be_exchange_name not between", value1, value2,
					"beExchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIsNull() {
			addCriterion("exchange_id is null");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIsNotNull() {
			addCriterion("exchange_id is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeIdEqualTo(Long value) {
			addCriterion("exchange_id =", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotEqualTo(Long value) {
			addCriterion("exchange_id <>", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdGreaterThan(Long value) {
			addCriterion("exchange_id >", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("exchange_id >=", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdLessThan(Long value) {
			addCriterion("exchange_id <", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdLessThanOrEqualTo(Long value) {
			addCriterion("exchange_id <=", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIn(List<Long> values) {
			addCriterion("exchange_id in", values, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotIn(List<Long> values) {
			addCriterion("exchange_id not in", values, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdBetween(Long value1, Long value2) {
			addCriterion("exchange_id between", value1, value2, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotBetween(Long value1, Long value2) {
			addCriterion("exchange_id not between", value1, value2,
					"exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeNameIsNull() {
			addCriterion("exchange_name is null");
			return (Criteria) this;
		}

		public Criteria andExchangeNameIsNotNull() {
			addCriterion("exchange_name is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeNameEqualTo(String value) {
			addCriterion("exchange_name =", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotEqualTo(String value) {
			addCriterion("exchange_name <>", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameGreaterThan(String value) {
			addCriterion("exchange_name >", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameGreaterThanOrEqualTo(String value) {
			addCriterion("exchange_name >=", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameLessThan(String value) {
			addCriterion("exchange_name <", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameLessThanOrEqualTo(String value) {
			addCriterion("exchange_name <=", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameLike(String value) {
			addCriterion("exchange_name like", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotLike(String value) {
			addCriterion("exchange_name not like", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameIn(List<String> values) {
			addCriterion("exchange_name in", values, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotIn(List<String> values) {
			addCriterion("exchange_name not in", values, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameBetween(String value1, String value2) {
			addCriterion("exchange_name between", value1, value2,
					"exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotBetween(String value1, String value2) {
			addCriterion("exchange_name not between", value1, value2,
					"exchangeName");
			return (Criteria) this;
		}

		public Criteria andOrderStateIsNull() {
			addCriterion("order_state is null");
			return (Criteria) this;
		}

		public Criteria andOrderStateIsNotNull() {
			addCriterion("order_state is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStateEqualTo(Integer value) {
			addCriterion("order_state =", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateNotEqualTo(Integer value) {
			addCriterion("order_state <>", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateGreaterThan(Integer value) {
			addCriterion("order_state >", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_state >=", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateLessThan(Integer value) {
			addCriterion("order_state <", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateLessThanOrEqualTo(Integer value) {
			addCriterion("order_state <=", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateIn(List<Integer> values) {
			addCriterion("order_state in", values, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateNotIn(List<Integer> values) {
			addCriterion("order_state not in", values, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateBetween(Integer value1, Integer value2) {
			addCriterion("order_state between", value1, value2, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateNotBetween(Integer value1, Integer value2) {
			addCriterion("order_state not between", value1, value2,
					"orderState");
			return (Criteria) this;
		}

		public Criteria andOrderTimeIsNull() {
			addCriterion("order_time is null");
			return (Criteria) this;
		}

		public Criteria andOrderTimeIsNotNull() {
			addCriterion("order_time is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTimeEqualTo(Date value) {
			addCriterion("order_time =", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeNotEqualTo(Date value) {
			addCriterion("order_time <>", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeGreaterThan(Date value) {
			addCriterion("order_time >", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("order_time >=", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeLessThan(Date value) {
			addCriterion("order_time <", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeLessThanOrEqualTo(Date value) {
			addCriterion("order_time <=", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeIn(List<Date> values) {
			addCriterion("order_time in", values, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeNotIn(List<Date> values) {
			addCriterion("order_time not in", values, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeBetween(Date value1, Date value2) {
			addCriterion("order_time between", value1, value2, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeNotBetween(Date value1, Date value2) {
			addCriterion("order_time not between", value1, value2, "orderTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeIsNull() {
			addCriterion("back_time is null");
			return (Criteria) this;
		}

		public Criteria andBackTimeIsNotNull() {
			addCriterion("back_time is not null");
			return (Criteria) this;
		}

		public Criteria andBackTimeEqualTo(Date value) {
			addCriterion("back_time =", value, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeNotEqualTo(Date value) {
			addCriterion("back_time <>", value, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeGreaterThan(Date value) {
			addCriterion("back_time >", value, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("back_time >=", value, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeLessThan(Date value) {
			addCriterion("back_time <", value, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeLessThanOrEqualTo(Date value) {
			addCriterion("back_time <=", value, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeIn(List<Date> values) {
			addCriterion("back_time in", values, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeNotIn(List<Date> values) {
			addCriterion("back_time not in", values, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeBetween(Date value1, Date value2) {
			addCriterion("back_time between", value1, value2, "backTime");
			return (Criteria) this;
		}

		public Criteria andBackTimeNotBetween(Date value1, Date value2) {
			addCriterion("back_time not between", value1, value2, "backTime");
			return (Criteria) this;
		}

		public Criteria andIssuedDateIsNull() {
			addCriterion("issued_date is null");
			return (Criteria) this;
		}

		public Criteria andIssuedDateIsNotNull() {
			addCriterion("issued_date is not null");
			return (Criteria) this;
		}

		public Criteria andIssuedDateEqualTo(Date value) {
			addCriterion("issued_date =", value, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateNotEqualTo(Date value) {
			addCriterion("issued_date <>", value, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateGreaterThan(Date value) {
			addCriterion("issued_date >", value, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("issued_date >=", value, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateLessThan(Date value) {
			addCriterion("issued_date <", value, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateLessThanOrEqualTo(Date value) {
			addCriterion("issued_date <=", value, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateIn(List<Date> values) {
			addCriterion("issued_date in", values, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateNotIn(List<Date> values) {
			addCriterion("issued_date not in", values, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateBetween(Date value1, Date value2) {
			addCriterion("issued_date between", value1, value2, "issuedDate");
			return (Criteria) this;
		}

		public Criteria andIssuedDateNotBetween(Date value1, Date value2) {
			addCriterion("issued_date not between", value1, value2,
					"issuedDate");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumIsNull() {
			addCriterion("be_exchange_num is null");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumIsNotNull() {
			addCriterion("be_exchange_num is not null");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumEqualTo(Long value) {
			addCriterion("be_exchange_num =", value, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumNotEqualTo(Long value) {
			addCriterion("be_exchange_num <>", value, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumGreaterThan(Long value) {
			addCriterion("be_exchange_num >", value, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumGreaterThanOrEqualTo(Long value) {
			addCriterion("be_exchange_num >=", value, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumLessThan(Long value) {
			addCriterion("be_exchange_num <", value, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumLessThanOrEqualTo(Long value) {
			addCriterion("be_exchange_num <=", value, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumIn(List<Long> values) {
			addCriterion("be_exchange_num in", values, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumNotIn(List<Long> values) {
			addCriterion("be_exchange_num not in", values, "beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumBetween(Long value1, Long value2) {
			addCriterion("be_exchange_num between", value1, value2,
					"beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andBeExchangeNumNotBetween(Long value1, Long value2) {
			addCriterion("be_exchange_num not between", value1, value2,
					"beExchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumIsNull() {
			addCriterion("exchange_num is null");
			return (Criteria) this;
		}

		public Criteria andExchangeNumIsNotNull() {
			addCriterion("exchange_num is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeNumEqualTo(Long value) {
			addCriterion("exchange_num =", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumNotEqualTo(Long value) {
			addCriterion("exchange_num <>", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumGreaterThan(Long value) {
			addCriterion("exchange_num >", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumGreaterThanOrEqualTo(Long value) {
			addCriterion("exchange_num >=", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumLessThan(Long value) {
			addCriterion("exchange_num <", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumLessThanOrEqualTo(Long value) {
			addCriterion("exchange_num <=", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumIn(List<Long> values) {
			addCriterion("exchange_num in", values, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumNotIn(List<Long> values) {
			addCriterion("exchange_num not in", values, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumBetween(Long value1, Long value2) {
			addCriterion("exchange_num between", value1, value2, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumNotBetween(Long value1, Long value2) {
			addCriterion("exchange_num not between", value1, value2,
					"exchangeNum");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andBackup1IsNull() {
			addCriterion("backup1 is null");
			return (Criteria) this;
		}

		public Criteria andBackup1IsNotNull() {
			addCriterion("backup1 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup1EqualTo(String value) {
			addCriterion("backup1 =", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotEqualTo(String value) {
			addCriterion("backup1 <>", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1GreaterThan(String value) {
			addCriterion("backup1 >", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1GreaterThanOrEqualTo(String value) {
			addCriterion("backup1 >=", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1LessThan(String value) {
			addCriterion("backup1 <", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1LessThanOrEqualTo(String value) {
			addCriterion("backup1 <=", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1Like(String value) {
			addCriterion("backup1 like", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotLike(String value) {
			addCriterion("backup1 not like", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1In(List<String> values) {
			addCriterion("backup1 in", values, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotIn(List<String> values) {
			addCriterion("backup1 not in", values, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1Between(String value1, String value2) {
			addCriterion("backup1 between", value1, value2, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotBetween(String value1, String value2) {
			addCriterion("backup1 not between", value1, value2, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup2IsNull() {
			addCriterion("backup2 is null");
			return (Criteria) this;
		}

		public Criteria andBackup2IsNotNull() {
			addCriterion("backup2 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup2EqualTo(String value) {
			addCriterion("backup2 =", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotEqualTo(String value) {
			addCriterion("backup2 <>", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2GreaterThan(String value) {
			addCriterion("backup2 >", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2GreaterThanOrEqualTo(String value) {
			addCriterion("backup2 >=", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2LessThan(String value) {
			addCriterion("backup2 <", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2LessThanOrEqualTo(String value) {
			addCriterion("backup2 <=", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2Like(String value) {
			addCriterion("backup2 like", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotLike(String value) {
			addCriterion("backup2 not like", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2In(List<String> values) {
			addCriterion("backup2 in", values, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotIn(List<String> values) {
			addCriterion("backup2 not in", values, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2Between(String value1, String value2) {
			addCriterion("backup2 between", value1, value2, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotBetween(String value1, String value2) {
			addCriterion("backup2 not between", value1, value2, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup3IsNull() {
			addCriterion("backup3 is null");
			return (Criteria) this;
		}

		public Criteria andBackup3IsNotNull() {
			addCriterion("backup3 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup3EqualTo(String value) {
			addCriterion("backup3 =", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotEqualTo(String value) {
			addCriterion("backup3 <>", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3GreaterThan(String value) {
			addCriterion("backup3 >", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3GreaterThanOrEqualTo(String value) {
			addCriterion("backup3 >=", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3LessThan(String value) {
			addCriterion("backup3 <", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3LessThanOrEqualTo(String value) {
			addCriterion("backup3 <=", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3Like(String value) {
			addCriterion("backup3 like", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotLike(String value) {
			addCriterion("backup3 not like", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3In(List<String> values) {
			addCriterion("backup3 in", values, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotIn(List<String> values) {
			addCriterion("backup3 not in", values, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3Between(String value1, String value2) {
			addCriterion("backup3 between", value1, value2, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotBetween(String value1, String value2) {
			addCriterion("backup3 not between", value1, value2, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup4IsNull() {
			addCriterion("backup4 is null");
			return (Criteria) this;
		}

		public Criteria andBackup4IsNotNull() {
			addCriterion("backup4 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup4EqualTo(String value) {
			addCriterion("backup4 =", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotEqualTo(String value) {
			addCriterion("backup4 <>", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4GreaterThan(String value) {
			addCriterion("backup4 >", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4GreaterThanOrEqualTo(String value) {
			addCriterion("backup4 >=", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4LessThan(String value) {
			addCriterion("backup4 <", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4LessThanOrEqualTo(String value) {
			addCriterion("backup4 <=", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4Like(String value) {
			addCriterion("backup4 like", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotLike(String value) {
			addCriterion("backup4 not like", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4In(List<String> values) {
			addCriterion("backup4 in", values, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotIn(List<String> values) {
			addCriterion("backup4 not in", values, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4Between(String value1, String value2) {
			addCriterion("backup4 between", value1, value2, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotBetween(String value1, String value2) {
			addCriterion("backup4 not between", value1, value2, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup5IsNull() {
			addCriterion("backup5 is null");
			return (Criteria) this;
		}

		public Criteria andBackup5IsNotNull() {
			addCriterion("backup5 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup5EqualTo(String value) {
			addCriterion("backup5 =", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotEqualTo(String value) {
			addCriterion("backup5 <>", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5GreaterThan(String value) {
			addCriterion("backup5 >", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5GreaterThanOrEqualTo(String value) {
			addCriterion("backup5 >=", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5LessThan(String value) {
			addCriterion("backup5 <", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5LessThanOrEqualTo(String value) {
			addCriterion("backup5 <=", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5Like(String value) {
			addCriterion("backup5 like", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotLike(String value) {
			addCriterion("backup5 not like", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5In(List<String> values) {
			addCriterion("backup5 in", values, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotIn(List<String> values) {
			addCriterion("backup5 not in", values, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5Between(String value1, String value2) {
			addCriterion("backup5 between", value1, value2, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotBetween(String value1, String value2) {
			addCriterion("backup5 not between", value1, value2, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup6IsNull() {
			addCriterion("backup6 is null");
			return (Criteria) this;
		}

		public Criteria andBackup6IsNotNull() {
			addCriterion("backup6 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup6EqualTo(String value) {
			addCriterion("backup6 =", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6NotEqualTo(String value) {
			addCriterion("backup6 <>", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6GreaterThan(String value) {
			addCriterion("backup6 >", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6GreaterThanOrEqualTo(String value) {
			addCriterion("backup6 >=", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6LessThan(String value) {
			addCriterion("backup6 <", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6LessThanOrEqualTo(String value) {
			addCriterion("backup6 <=", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6Like(String value) {
			addCriterion("backup6 like", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6NotLike(String value) {
			addCriterion("backup6 not like", value, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6In(List<String> values) {
			addCriterion("backup6 in", values, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6NotIn(List<String> values) {
			addCriterion("backup6 not in", values, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6Between(String value1, String value2) {
			addCriterion("backup6 between", value1, value2, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup6NotBetween(String value1, String value2) {
			addCriterion("backup6 not between", value1, value2, "backup6");
			return (Criteria) this;
		}

		public Criteria andBackup7IsNull() {
			addCriterion("backup7 is null");
			return (Criteria) this;
		}

		public Criteria andBackup7IsNotNull() {
			addCriterion("backup7 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup7EqualTo(String value) {
			addCriterion("backup7 =", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7NotEqualTo(String value) {
			addCriterion("backup7 <>", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7GreaterThan(String value) {
			addCriterion("backup7 >", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7GreaterThanOrEqualTo(String value) {
			addCriterion("backup7 >=", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7LessThan(String value) {
			addCriterion("backup7 <", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7LessThanOrEqualTo(String value) {
			addCriterion("backup7 <=", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7Like(String value) {
			addCriterion("backup7 like", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7NotLike(String value) {
			addCriterion("backup7 not like", value, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7In(List<String> values) {
			addCriterion("backup7 in", values, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7NotIn(List<String> values) {
			addCriterion("backup7 not in", values, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7Between(String value1, String value2) {
			addCriterion("backup7 between", value1, value2, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup7NotBetween(String value1, String value2) {
			addCriterion("backup7 not between", value1, value2, "backup7");
			return (Criteria) this;
		}

		public Criteria andBackup8IsNull() {
			addCriterion("backup8 is null");
			return (Criteria) this;
		}

		public Criteria andBackup8IsNotNull() {
			addCriterion("backup8 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup8EqualTo(String value) {
			addCriterion("backup8 =", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8NotEqualTo(String value) {
			addCriterion("backup8 <>", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8GreaterThan(String value) {
			addCriterion("backup8 >", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8GreaterThanOrEqualTo(String value) {
			addCriterion("backup8 >=", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8LessThan(String value) {
			addCriterion("backup8 <", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8LessThanOrEqualTo(String value) {
			addCriterion("backup8 <=", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8Like(String value) {
			addCriterion("backup8 like", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8NotLike(String value) {
			addCriterion("backup8 not like", value, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8In(List<String> values) {
			addCriterion("backup8 in", values, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8NotIn(List<String> values) {
			addCriterion("backup8 not in", values, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8Between(String value1, String value2) {
			addCriterion("backup8 between", value1, value2, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup8NotBetween(String value1, String value2) {
			addCriterion("backup8 not between", value1, value2, "backup8");
			return (Criteria) this;
		}

		public Criteria andBackup9IsNull() {
			addCriterion("backup9 is null");
			return (Criteria) this;
		}

		public Criteria andBackup9IsNotNull() {
			addCriterion("backup9 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup9EqualTo(String value) {
			addCriterion("backup9 =", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9NotEqualTo(String value) {
			addCriterion("backup9 <>", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9GreaterThan(String value) {
			addCriterion("backup9 >", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9GreaterThanOrEqualTo(String value) {
			addCriterion("backup9 >=", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9LessThan(String value) {
			addCriterion("backup9 <", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9LessThanOrEqualTo(String value) {
			addCriterion("backup9 <=", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9Like(String value) {
			addCriterion("backup9 like", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9NotLike(String value) {
			addCriterion("backup9 not like", value, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9In(List<String> values) {
			addCriterion("backup9 in", values, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9NotIn(List<String> values) {
			addCriterion("backup9 not in", values, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9Between(String value1, String value2) {
			addCriterion("backup9 between", value1, value2, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup9NotBetween(String value1, String value2) {
			addCriterion("backup9 not between", value1, value2, "backup9");
			return (Criteria) this;
		}

		public Criteria andBackup10IsNull() {
			addCriterion("backup10 is null");
			return (Criteria) this;
		}

		public Criteria andBackup10IsNotNull() {
			addCriterion("backup10 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup10EqualTo(String value) {
			addCriterion("backup10 =", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10NotEqualTo(String value) {
			addCriterion("backup10 <>", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10GreaterThan(String value) {
			addCriterion("backup10 >", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10GreaterThanOrEqualTo(String value) {
			addCriterion("backup10 >=", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10LessThan(String value) {
			addCriterion("backup10 <", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10LessThanOrEqualTo(String value) {
			addCriterion("backup10 <=", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10Like(String value) {
			addCriterion("backup10 like", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10NotLike(String value) {
			addCriterion("backup10 not like", value, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10In(List<String> values) {
			addCriterion("backup10 in", values, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10NotIn(List<String> values) {
			addCriterion("backup10 not in", values, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10Between(String value1, String value2) {
			addCriterion("backup10 between", value1, value2, "backup10");
			return (Criteria) this;
		}

		public Criteria andBackup10NotBetween(String value1, String value2) {
			addCriterion("backup10 not between", value1, value2, "backup10");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hs_exchange_order
     *
     * @mbggenerated do_not_delete_during_merge Thu May 21 15:19:09 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}