package com.cbice.distribute.core.db.model;

import java.util.List;

public class TAgencyUserBean {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.assets_account
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String assetsAccount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.rights_account
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String rightsAccount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_name
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.address
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.dealer_level
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Integer dealerLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_role
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Long userRole;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.dealer_num
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String dealerNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.dealer_name
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String dealerName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_identy
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Integer userIdenty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.tel
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.email
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.sex
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Integer sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.certificate_num
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private String certificateNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.account_status
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Integer accountStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.higer_dealer
	 * @mbggenerated  Tue Mar 10 18:35:19 CST 2015
	 */
	private Long higerDealer;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.assets_account
	 * @return  the value of t_user.assets_account
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getAssetsAccount() {
		return assetsAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.assets_account
	 * @param assetsAccount  the value for t_user.assets_account
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setAssetsAccount(String assetsAccount) {
		this.assetsAccount = assetsAccount == null ? null : assetsAccount
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.rights_account
	 * @return  the value of t_user.rights_account
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getRightsAccount() {
		return rightsAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.rights_account
	 * @param rightsAccount  the value for t_user.rights_account
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setRightsAccount(String rightsAccount) {
		this.rightsAccount = rightsAccount == null ? null : rightsAccount
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_name
	 * @return  the value of t_user.user_name
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_name
	 * @param userName  the value for t_user.user_name
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.tel
	 * @return  the value of t_user.tel
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.tel
	 * @param tel  the value for t_user.tel
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.address
	 * @return  the value of t_user.address
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.address
	 * @param address  the value for t_user.address
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	public Integer getDealerLevel() {
		return dealerLevel;
	}

	public void setDealerLevel(Integer dealerLevel) {
		this.dealerLevel = dealerLevel;
	}

	public Long getUserRole() {
		return userRole;
	}

	public void setUserRole(Long userRole) {
		this.userRole = userRole;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getCertificateNum() {
		return certificateNum;
	}

	public void setCertificateNum(String certificateNum) {
		this.certificateNum = certificateNum;
	}

	public Integer getAccountStatus() {
		return accountStatus;
	}

	public void setAccountStatus(Integer accountStatus) {
		this.accountStatus = accountStatus;
	}

	public Long getHigerDealer() {
		return higerDealer;
	}

	public void setHigerDealer(Long higerDealer) {
		this.higerDealer = higerDealer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.dealer_num
	 * @return  the value of t_user.dealer_num
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getDealerNum() {
		return dealerNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.dealer_num
	 * @param dealerNum  the value for t_user.dealer_num
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setDealerNum(String dealerNum) {
		this.dealerNum = dealerNum == null ? null : dealerNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.dealer_name
	 * @return  the value of t_user.dealer_name
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public String getDealerName() {
		return dealerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.dealer_name
	 * @param dealerName  the value for t_user.dealer_name
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setDealerName(String dealerName) {
		this.dealerName = dealerName == null ? null : dealerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_identy
	 * @return  the value of t_user.user_identy
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public Integer getUserIdenty() {
		return userIdenty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_identy
	 * @param userIdenty  the value for t_user.user_identy
	 * @mbggenerated  Sat Feb 28 13:22:34 CST 2015
	 */
	public void setUserIdenty(Integer userIdenty) {
		this.userIdenty = userIdenty;
	}

    private List<TAgencyBusiRole> tAgencyBusiRoles;
    
  

    public List<TAgencyBusiRole> gettAgencyBusiRoles(){
        return tAgencyBusiRoles;
    }

    public void settAgencyBusiRoles(List<TAgencyBusiRole> tAgencyBusiRoles){
        this.tAgencyBusiRoles = tAgencyBusiRoles;
    }

   
}
