package com.cbice.distribute.core.db.model;

import java.util.Date;

public class TAgency {

    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.id
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.dealer_name
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private String dealerName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.dealer_num
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private String dealerNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.dealer_level
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private Integer dealerLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.higer_dealer_id
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private Long higerDealerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.lft
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private Integer lft;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.rgt
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private Integer rgt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency.modify_time
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.id
	 * @return  the value of t_agency.id
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.id
	 * @param id  the value for t_agency.id
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.dealer_name
	 * @return  the value of t_agency.dealer_name
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public String getDealerName() {
		return dealerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.dealer_name
	 * @param dealerName  the value for t_agency.dealer_name
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setDealerName(String dealerName) {
		this.dealerName = dealerName == null ? null : dealerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.dealer_num
	 * @return  the value of t_agency.dealer_num
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public String getDealerNum() {
		return dealerNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.dealer_num
	 * @param dealerNum  the value for t_agency.dealer_num
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setDealerNum(String dealerNum) {
		this.dealerNum = dealerNum == null ? null : dealerNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.dealer_level
	 * @return  the value of t_agency.dealer_level
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public Integer getDealerLevel() {
		return dealerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.dealer_level
	 * @param dealerLevel  the value for t_agency.dealer_level
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setDealerLevel(Integer dealerLevel) {
		this.dealerLevel = dealerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.higer_dealer_id
	 * @return  the value of t_agency.higer_dealer_id
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public Long getHigerDealerId() {
		return higerDealerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.higer_dealer_id
	 * @param higerDealerId  the value for t_agency.higer_dealer_id
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setHigerDealerId(Long higerDealerId) {
		this.higerDealerId = higerDealerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.lft
	 * @return  the value of t_agency.lft
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public Integer getLft() {
		return lft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.lft
	 * @param lft  the value for t_agency.lft
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setLft(Integer lft) {
		this.lft = lft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.rgt
	 * @return  the value of t_agency.rgt
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public Integer getRgt() {
		return rgt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.rgt
	 * @param rgt  the value for t_agency.rgt
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency.modify_time
	 * @return  the value of t_agency.modify_time
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency.modify_time
	 * @param modifyTime  the value for t_agency.modify_time
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * 分页�?
	 */
	private int limit;
	
	private int start;
    
    private Long agencyId;
    
    private String higerDealer;
    
    private String stringDealerLevel;
    
    private String userName;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getLimit() {
		return limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getStart() {
		return start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	public Long getAgencyId() {
		return agencyId;
	}

	public void setAgencyId(Long agencyId) {
		this.agencyId = agencyId;
	}

	public String getHigerDealer() {
		return higerDealer;
	}

	public void setHigerDealer(String higerDealer) {
		this.higerDealer = higerDealer;
	}

	public String getStringDealerLevel() {
		return stringDealerLevel;
	}

	public void setStringDealerLevel(String stringDealerLevel) {
		this.stringDealerLevel = stringDealerLevel;
	}
    
    
}