package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsCommodity;
import com.cbice.distribute.core.db.model.HsCommodityExample;
import com.cbice.distribute.core.db.model.HsCommodityRule;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsCommodityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int countByExample(HsCommodityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int deleteByExample(HsCommodityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int deleteByPrimaryKey(@Param("comId") Long comId,
			@Param("sysId") String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int insert(HsCommodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int insertSelective(HsCommodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	List<HsCommodity> selectByExample(HsCommodityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	HsCommodity selectByPrimaryKey(@Param("comId") Long comId,
			@Param("sysId") String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsCommodity record,
			@Param("example") HsCommodityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByExample(@Param("record") HsCommodity record,
			@Param("example") HsCommodityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByPrimaryKeySelective(HsCommodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByPrimaryKey(HsCommodity record);

	List<Map> commodityQuery(Map<String, Object> map);
	
	int countSelectBy(Map<String,Object> map);
	
	List<HsCommodity> commodityQueryBean(Map<String, Object> map);
	
	List<HsCommodity> queryProductType(Map<String, Object> map);
	
	List<HsCommodityRule> queryRulesById(Long comId);
	
	int updateCurrencyNumAndFreezeNum(HsCommodity hsCommodity); 
	
	List<Map> queryLoadItemName(Map<String, Object> map);

	List<Map> queryLoadComName(Map<String, Object> map);

	List<Map> commodityQueryList(Map<String, Object> map);

	int countCommodityQueryList(Map<String, Object> map);

	HsCommodity selectBycomName(Map<String, Object> map);
	
	HsCommodity queryexchangeId(Map<String, Object> map);

	int insertNewComdity(Map<String, Object> map);

	List<Map<String, Object>> exchangeRuleQuery(Map<String, Object> map);
	
	 int updateCommodityById(Map<String ,Object> map);
	 
	 int deleteCommodityById(Map<String, Object> map);

	int updateByPrimaryKeyAndVersion(HsCommodity record);
}