package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsExchangeGift;
import com.cbice.distribute.core.db.model.HsExchangeGiftExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsExchangeGiftMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int countByExample(HsExchangeGiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int deleteByExample(HsExchangeGiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insert(HsExchangeGift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insertSelective(HsExchangeGift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	List<HsExchangeGift> selectByExample(HsExchangeGiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsExchangeGift record,
			@Param("example") HsExchangeGiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_gift
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExample(@Param("record") HsExchangeGift record,
			@Param("example") HsExchangeGiftExample example);

	List<HsExchangeGift> selectGifeById(Map<String,Object> map);
}