package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TAccessGold;
import com.cbice.distribute.core.db.model.TAccessGoldExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TAccessGoldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    int countByExample(TAccessGoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    int deleteByExample(TAccessGoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    int insert(TAccessGold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    int insertSelective(TAccessGold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    List<TAccessGold> selectByExample(TAccessGoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    int updateByExampleSelective(@Param("record") TAccessGold record, @Param("example") TAccessGoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_gold
     *
     * @mbggenerated Fri May 15 15:50:34 CST 2015
     */
    int updateByExample(@Param("record") TAccessGold record, @Param("example") TAccessGoldExample example);

	List<TAccessGold> selectAccessGold(TAccessGold accessGold);

	List<Map> selectAccessGold(Map<String, Object> map);

	List<TAccessGold> selectAccessGoldAll(Map<String, Object> map);

	int selectAccessGoldCount(Map<String, Object> map);
	
	
	int selectAccessGoldCountSum(Map<String, Object> map);
	
	List<Map> selectAccessGoldSum(Map<String, Object> map);
	
	List<TAccessGold> selectAccessGoldAllSum(Map<String, Object> map);

	int queryMaxDate();
}