package com.cbice.distribute.core.db.data;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cbice.distribute.core.db.model.TGoods;
import com.cbice.distribute.core.db.model.TGoodsExample;

public interface TGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int countByExample(TGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int deleteByExample(TGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int insert(TGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int insertSelective(TGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	List<TGoods> selectByExample(TGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	TGoods selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TGoods record,
			@Param("example") TGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int updateByExample(@Param("record") TGoods record,
			@Param("example") TGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int updateByPrimaryKeySelective(TGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods
	 * @mbggenerated  Fri Mar 20 14:17:44 CST 2015
	 */
	int updateByPrimaryKey(TGoods record);

	/**
	 * 查找产品信息
	 * @param map
	 * @return
	 */
	List<TGoods> selectBygoodsNumOrGoodsName(Map<String,Object> map);
	
	int countSlectgoodsNumorGoodsName(Map<String,Object> map);
	/**
	 * 查询唯一产品信息
	 * @param map
	 * @return
	 */
	 TGoods selectOnlyGoodsNumOrGoodsName(Map<String,Object> map);

	 int selectGoodsCount(int userId);
	 
	 TGoods selectBygoodsNum(Map<String,Object> map);
	 
	 int checkTgoodsNumEqualsTgoodsCount(Map<String,Object> map);
	 
	 int selectCountGoodsNumOrGoodsName(Map<String,Object> map);
}