package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TGoodsOrder;
import com.cbice.distribute.core.db.model.TGoodsOrderExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TGoodsOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int countByExample(TGoodsOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int deleteByExample(TGoodsOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int insert(TGoodsOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int insertSelective(TGoodsOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	List<TGoodsOrder> selectByExample(TGoodsOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	TGoodsOrder selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TGoodsOrder record,
			@Param("example") TGoodsOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int updateByExample(@Param("record") TGoodsOrder record,
			@Param("example") TGoodsOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int updateByPrimaryKeySelective(TGoodsOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order
	 * @mbggenerated  Mon Mar 23 09:35:43 CST 2015
	 */
	int updateByPrimaryKey(TGoodsOrder record);

	List<Map<String, Object>> selectBy(Map<String,Object> map);
	
	int countSelectBy(Map<String,Object> map);
	
	List<Map<String, Object>> selectReturnGoodsList(Map<String,Object> map);
	
	int selectReturnGoodsListCount(Map<String,Object> map);
	
	String selectDealerNameById(@Param(value="agencyId")Long agencyId);

	List<TGoodsOrder> selectHistoryGoodsOrderBy(Map<String, Object> map);
	
	int countSelectHistoryGoodsOrderBy(Map<String, Object> map);
	
	List<TGoodsOrder> selectToSendBuyUserid(Map<String, Object> paramMap);
	
	int countSelectToSendBuyUserid(Map<String, Object> paramMap);
	/**
	 * �?��码导�?
	 * @param map
	 * @return
	 */
	List<TGoodsOrder> outSaleCode(Map<String,Object> map);

	List<TGoodsOrder> selectGoodsOrderByBatchid(@Param(value="batchId")long batchId);
	List<TGoodsOrder> selectReturnGoodsOrderByBatchid(long batchId);
	/**
	 * 登陆线上登陆系统
	 * @param map
	 * @return
	 */
//	List<TGoodsOrder> selectUserMerberbyAccount(String account);

	List<TGoodsOrder> selectUserMemberbyOrder(Map<String,Object> map);

	String selectUserNameById(@Param(value="userId")Long userId);

	Long selectUseridentyById(@Param(value="userId")Long userId);

	List<TGoodsOrder> selectGoodsBatchById(@Param(value="batchId")Long batchId);
   /**
    * 	查询�?��订单
    * @param map
    * @return
    */
	List<TGoodsOrder> selectOrderbyUserIdgoodsNameGoodsNum(Map<String,Object> map);
	/**
	 * 查询历史购买记录
	 * @param map
	 * @return
	 */
	List<TGoodsOrder> selectHistoryGoodsOrder(Map<String, Object> map);
	
	List<TGoodsOrder> selectReturnGoodsHis(Map<String, Object> map);
	
	int selectReturnGoodsHisCount(Map<String, Object> paramMap);
	
	Map<String,Object> selectHistoryGoodsOrderCount(Map<String,Object> paramMap);
	
	TGoodsOrder  selectOrderbySerial(Map<String,Object> paramMap);
	
	List<TGoodsOrder> TranctionOut(Map<String, Object> paramMap);
	
	List<TGoodsOrder> selectMemberHistoryGoodsOrderBy(Map<String, Object> map);
	
	int countSelectMemberHistoryGoodsOrderBy(Map<String, Object> paramMap);
	
}