package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.THisOtcrealtime;
import com.cbice.distribute.core.db.model.THisOtcrealtimeExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface THisOtcrealtimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int countByExample(THisOtcrealtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int deleteByExample(THisOtcrealtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int insert(THisOtcrealtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int insertSelective(THisOtcrealtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    List<THisOtcrealtime> selectByExample(THisOtcrealtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") THisOtcrealtime record, @Param("example") THisOtcrealtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcrealtime
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int updateByExample(@Param("record") THisOtcrealtime record, @Param("example") THisOtcrealtimeExample example);

	List<Map<String, Object>> CommissionQuery(Map<String, Object> map);

	int countSelectBy(Map<String, Object> map);

	List<THisOtcrealtime> commissionQueryAll(Map<String, Object> map);
    
	
	int countSelectBySum(Map<String, Object> map);
	
	List<Map<String,Object>> CommissionQuerySum(Map<String, Object> map);
	
	List<THisOtcrealtime> commissionQueryAllSum(Map<String, Object> map);

	int queryMaxdate();
    
}