package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TSysUserBusiRole;
import com.cbice.distribute.core.db.model.TSysUserBusiRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysUserBusiRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int countByExample(TSysUserBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int deleteByExample(TSysUserBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("busiRoleId") Long busiRoleId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int insert(TSysUserBusiRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int insertSelective(TSysUserBusiRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    List<TSysUserBusiRole> selectByExample(TSysUserBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysUserBusiRole record, @Param("example") TSysUserBusiRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_user_busi_role
     * @mbggenerated  Tue Feb 17 06:40:38 CST 2015
     */
    int updateByExample(@Param("record") TSysUserBusiRole record, @Param("example") TSysUserBusiRoleExample example);
}