package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TUser;
import com.cbice.distribute.core.db.model.VUserAgency;
import com.cbice.distribute.core.db.model.VUserAgencyExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface VUserAgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    int countByExample(VUserAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    int deleteByExample(VUserAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    int insert(VUserAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    int insertSelective(VUserAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    List<VUserAgency> selectByExample(VUserAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") VUserAgency record, @Param("example") VUserAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user_agency
     *
     * @mbggenerated Thu Mar 12 21:23:18 CST 2015
     */
    int updateByExample(@Param("record") VUserAgency record, @Param("example") VUserAgencyExample example);
    
    
    
    
    
   
	VUserAgency selectById(Long id) ;
	
	List<VUserAgency> selectAllByHigerAgencyId(Long id);
	
	
    List<VUserAgency> selectUsersByHigerAgencyId(Long id);
	
	
	
	List<VUserAgency> selectAgenciesByHigerAgencyId(Long id);
	List<VUserAgency> selectLowerDealer(Map<String,Object> map);
	int countselectLowerDealer(Map<String,Object> map);
}