package com.cbice.distribute.core.db.model;

import java.util.Date;

public class HsCommodity {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.com_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long comId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.sys_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String sysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.com_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String comName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.item_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String itemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.list_organization
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String listOrganization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.sale_unit
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String saleUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.sale_price
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Double salePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.sale_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long saleNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.sale_money
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Double saleMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.currency_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long currencyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.freeze_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long freezeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.start_date
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.end_date
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.com_picture
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String comPicture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.exchange_state
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Integer exchangeState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.min_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Integer minNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.introduction
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.version
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Long version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.modify_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String modifyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.modify_time
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup1
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup2
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup3
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup4
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup5
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup6
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup7
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup8
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup9
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hs_commodity.backup10
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	private String backup10;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.com_id
	 * @return  the value of hs_commodity.com_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getComId() {
		return comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.com_id
	 * @param comId  the value for hs_commodity.com_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setComId(Long comId) {
		this.comId = comId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.sys_id
	 * @return  the value of hs_commodity.sys_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getSysId() {
		return sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.sys_id
	 * @param sysId  the value for hs_commodity.sys_id
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId == null ? null : sysId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.com_name
	 * @return  the value of hs_commodity.com_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getComName() {
		return comName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.com_name
	 * @param comName  the value for hs_commodity.com_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setComName(String comName) {
		this.comName = comName == null ? null : comName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.item_name
	 * @return  the value of hs_commodity.item_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.item_name
	 * @param itemName  the value for hs_commodity.item_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName == null ? null : itemName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.list_organization
	 * @return  the value of hs_commodity.list_organization
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getListOrganization() {
		return listOrganization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.list_organization
	 * @param listOrganization  the value for hs_commodity.list_organization
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setListOrganization(String listOrganization) {
		this.listOrganization = listOrganization == null ? null
				: listOrganization.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.sale_unit
	 * @return  the value of hs_commodity.sale_unit
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getSaleUnit() {
		return saleUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.sale_unit
	 * @param saleUnit  the value for hs_commodity.sale_unit
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setSaleUnit(String saleUnit) {
		this.saleUnit = saleUnit == null ? null : saleUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.sale_price
	 * @return  the value of hs_commodity.sale_price
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Double getSalePrice() {
		return salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.sale_price
	 * @param salePrice  the value for hs_commodity.sale_price
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.sale_num
	 * @return  the value of hs_commodity.sale_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getSaleNum() {
		return saleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.sale_num
	 * @param saleNum  the value for hs_commodity.sale_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setSaleNum(Long saleNum) {
		this.saleNum = saleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.sale_money
	 * @return  the value of hs_commodity.sale_money
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Double getSaleMoney() {
		return saleMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.sale_money
	 * @param saleMoney  the value for hs_commodity.sale_money
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setSaleMoney(Double saleMoney) {
		this.saleMoney = saleMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.currency_num
	 * @return  the value of hs_commodity.currency_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getCurrencyNum() {
		return currencyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.currency_num
	 * @param currencyNum  the value for hs_commodity.currency_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setCurrencyNum(Long currencyNum) {
		this.currencyNum = currencyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.freeze_num
	 * @return  the value of hs_commodity.freeze_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getFreezeNum() {
		return freezeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.freeze_num
	 * @param freezeNum  the value for hs_commodity.freeze_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setFreezeNum(Long freezeNum) {
		this.freezeNum = freezeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.start_date
	 * @return  the value of hs_commodity.start_date
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.start_date
	 * @param startDate  the value for hs_commodity.start_date
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.end_date
	 * @return  the value of hs_commodity.end_date
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.end_date
	 * @param endDate  the value for hs_commodity.end_date
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.com_picture
	 * @return  the value of hs_commodity.com_picture
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getComPicture() {
		return comPicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.com_picture
	 * @param comPicture  the value for hs_commodity.com_picture
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setComPicture(String comPicture) {
		this.comPicture = comPicture == null ? null : comPicture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.exchange_state
	 * @return  the value of hs_commodity.exchange_state
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Integer getExchangeState() {
		return exchangeState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.exchange_state
	 * @param exchangeState  the value for hs_commodity.exchange_state
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setExchangeState(Integer exchangeState) {
		this.exchangeState = exchangeState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.min_num
	 * @return  the value of hs_commodity.min_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Integer getMinNum() {
		return minNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.min_num
	 * @param minNum  the value for hs_commodity.min_num
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setMinNum(Integer minNum) {
		this.minNum = minNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.introduction
	 * @return  the value of hs_commodity.introduction
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.introduction
	 * @param introduction  the value for hs_commodity.introduction
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.version
	 * @return  the value of hs_commodity.version
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Long getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.version
	 * @param version  the value for hs_commodity.version
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setVersion(Long version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.modify_name
	 * @return  the value of hs_commodity.modify_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getModifyName() {
		return modifyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.modify_name
	 * @param modifyName  the value for hs_commodity.modify_name
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setModifyName(String modifyName) {
		this.modifyName = modifyName == null ? null : modifyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.modify_time
	 * @return  the value of hs_commodity.modify_time
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.modify_time
	 * @param modifyTime  the value for hs_commodity.modify_time
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup1
	 * @return  the value of hs_commodity.backup1
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup1() {
		return backup1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup1
	 * @param backup1  the value for hs_commodity.backup1
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup1(String backup1) {
		this.backup1 = backup1 == null ? null : backup1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup2
	 * @return  the value of hs_commodity.backup2
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup2() {
		return backup2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup2
	 * @param backup2  the value for hs_commodity.backup2
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup2(String backup2) {
		this.backup2 = backup2 == null ? null : backup2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup3
	 * @return  the value of hs_commodity.backup3
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup3() {
		return backup3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup3
	 * @param backup3  the value for hs_commodity.backup3
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup3(String backup3) {
		this.backup3 = backup3 == null ? null : backup3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup4
	 * @return  the value of hs_commodity.backup4
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup4() {
		return backup4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup4
	 * @param backup4  the value for hs_commodity.backup4
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup4(String backup4) {
		this.backup4 = backup4 == null ? null : backup4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup5
	 * @return  the value of hs_commodity.backup5
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup5() {
		return backup5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup5
	 * @param backup5  the value for hs_commodity.backup5
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup5(String backup5) {
		this.backup5 = backup5 == null ? null : backup5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup6
	 * @return  the value of hs_commodity.backup6
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup6() {
		return backup6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup6
	 * @param backup6  the value for hs_commodity.backup6
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup6(String backup6) {
		this.backup6 = backup6 == null ? null : backup6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup7
	 * @return  the value of hs_commodity.backup7
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup7() {
		return backup7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup7
	 * @param backup7  the value for hs_commodity.backup7
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup7(String backup7) {
		this.backup7 = backup7 == null ? null : backup7.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup8
	 * @return  the value of hs_commodity.backup8
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup8() {
		return backup8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup8
	 * @param backup8  the value for hs_commodity.backup8
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup8(String backup8) {
		this.backup8 = backup8 == null ? null : backup8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup9
	 * @return  the value of hs_commodity.backup9
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup9() {
		return backup9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup9
	 * @param backup9  the value for hs_commodity.backup9
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup9(String backup9) {
		this.backup9 = backup9 == null ? null : backup9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hs_commodity.backup10
	 * @return  the value of hs_commodity.backup10
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getBackup10() {
		return backup10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hs_commodity.backup10
	 * @param backup10  the value for hs_commodity.backup10
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setBackup10(String backup10) {
		this.backup10 = backup10 == null ? null : backup10.trim();
	}

	private String startDate1;
    private String endDate1;
    private long giftNum;
    
   
	public long getGiftNum() {
		return giftNum;
	}

	public void setGiftNum(long giftNum) {
		this.giftNum = giftNum;
	}

	public String getStartDate1() {
		return startDate1;
	}

	public void setStartDate1(String startDate1) {
		this.startDate1 = startDate1;
	}

	public String getEndDate1() {
		return endDate1;
	}

	public void setEndDate1(String endDate1) {
		this.endDate1 = endDate1;
	}
    
}