package com.cbice.distribute.core.db.model;

import java.util.ArrayList;
import java.util.List;

public class HsCommodityRuleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public HsCommodityRuleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andComIdIsNull() {
			addCriterion("com_id is null");
			return (Criteria) this;
		}

		public Criteria andComIdIsNotNull() {
			addCriterion("com_id is not null");
			return (Criteria) this;
		}

		public Criteria andComIdEqualTo(Long value) {
			addCriterion("com_id =", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotEqualTo(Long value) {
			addCriterion("com_id <>", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThan(Long value) {
			addCriterion("com_id >", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdGreaterThanOrEqualTo(Long value) {
			addCriterion("com_id >=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThan(Long value) {
			addCriterion("com_id <", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdLessThanOrEqualTo(Long value) {
			addCriterion("com_id <=", value, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdIn(List<Long> values) {
			addCriterion("com_id in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotIn(List<Long> values) {
			addCriterion("com_id not in", values, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdBetween(Long value1, Long value2) {
			addCriterion("com_id between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andComIdNotBetween(Long value1, Long value2) {
			addCriterion("com_id not between", value1, value2, "comId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIsNull() {
			addCriterion("exchange_id is null");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIsNotNull() {
			addCriterion("exchange_id is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeIdEqualTo(Long value) {
			addCriterion("exchange_id =", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotEqualTo(Long value) {
			addCriterion("exchange_id <>", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdGreaterThan(Long value) {
			addCriterion("exchange_id >", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("exchange_id >=", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdLessThan(Long value) {
			addCriterion("exchange_id <", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdLessThanOrEqualTo(Long value) {
			addCriterion("exchange_id <=", value, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdIn(List<Long> values) {
			addCriterion("exchange_id in", values, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotIn(List<Long> values) {
			addCriterion("exchange_id not in", values, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdBetween(Long value1, Long value2) {
			addCriterion("exchange_id between", value1, value2, "exchangeId");
			return (Criteria) this;
		}

		public Criteria andExchangeIdNotBetween(Long value1, Long value2) {
			addCriterion("exchange_id not between", value1, value2,
					"exchangeId");
			return (Criteria) this;
		}

		public Criteria andSysIdIsNull() {
			addCriterion("sys_id is null");
			return (Criteria) this;
		}

		public Criteria andSysIdIsNotNull() {
			addCriterion("sys_id is not null");
			return (Criteria) this;
		}

		public Criteria andSysIdEqualTo(String value) {
			addCriterion("sys_id =", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotEqualTo(String value) {
			addCriterion("sys_id <>", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdGreaterThan(String value) {
			addCriterion("sys_id >", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdGreaterThanOrEqualTo(String value) {
			addCriterion("sys_id >=", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdLessThan(String value) {
			addCriterion("sys_id <", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdLessThanOrEqualTo(String value) {
			addCriterion("sys_id <=", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdLike(String value) {
			addCriterion("sys_id like", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotLike(String value) {
			addCriterion("sys_id not like", value, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdIn(List<String> values) {
			addCriterion("sys_id in", values, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotIn(List<String> values) {
			addCriterion("sys_id not in", values, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdBetween(String value1, String value2) {
			addCriterion("sys_id between", value1, value2, "sysId");
			return (Criteria) this;
		}

		public Criteria andSysIdNotBetween(String value1, String value2) {
			addCriterion("sys_id not between", value1, value2, "sysId");
			return (Criteria) this;
		}

		public Criteria andComNameIsNull() {
			addCriterion("com_name is null");
			return (Criteria) this;
		}

		public Criteria andComNameIsNotNull() {
			addCriterion("com_name is not null");
			return (Criteria) this;
		}

		public Criteria andComNameEqualTo(String value) {
			addCriterion("com_name =", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameNotEqualTo(String value) {
			addCriterion("com_name <>", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameGreaterThan(String value) {
			addCriterion("com_name >", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameGreaterThanOrEqualTo(String value) {
			addCriterion("com_name >=", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameLessThan(String value) {
			addCriterion("com_name <", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameLessThanOrEqualTo(String value) {
			addCriterion("com_name <=", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameLike(String value) {
			addCriterion("com_name like", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameNotLike(String value) {
			addCriterion("com_name not like", value, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameIn(List<String> values) {
			addCriterion("com_name in", values, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameNotIn(List<String> values) {
			addCriterion("com_name not in", values, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameBetween(String value1, String value2) {
			addCriterion("com_name between", value1, value2, "comName");
			return (Criteria) this;
		}

		public Criteria andComNameNotBetween(String value1, String value2) {
			addCriterion("com_name not between", value1, value2, "comName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameIsNull() {
			addCriterion("exchange_name is null");
			return (Criteria) this;
		}

		public Criteria andExchangeNameIsNotNull() {
			addCriterion("exchange_name is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeNameEqualTo(String value) {
			addCriterion("exchange_name =", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotEqualTo(String value) {
			addCriterion("exchange_name <>", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameGreaterThan(String value) {
			addCriterion("exchange_name >", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameGreaterThanOrEqualTo(String value) {
			addCriterion("exchange_name >=", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameLessThan(String value) {
			addCriterion("exchange_name <", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameLessThanOrEqualTo(String value) {
			addCriterion("exchange_name <=", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameLike(String value) {
			addCriterion("exchange_name like", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotLike(String value) {
			addCriterion("exchange_name not like", value, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameIn(List<String> values) {
			addCriterion("exchange_name in", values, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotIn(List<String> values) {
			addCriterion("exchange_name not in", values, "exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameBetween(String value1, String value2) {
			addCriterion("exchange_name between", value1, value2,
					"exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNameNotBetween(String value1, String value2) {
			addCriterion("exchange_name not between", value1, value2,
					"exchangeName");
			return (Criteria) this;
		}

		public Criteria andExchangeNumIsNull() {
			addCriterion("exchange_num is null");
			return (Criteria) this;
		}

		public Criteria andExchangeNumIsNotNull() {
			addCriterion("exchange_num is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeNumEqualTo(Long value) {
			addCriterion("exchange_num =", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumNotEqualTo(Long value) {
			addCriterion("exchange_num <>", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumGreaterThan(Long value) {
			addCriterion("exchange_num >", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumGreaterThanOrEqualTo(Long value) {
			addCriterion("exchange_num >=", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumLessThan(Long value) {
			addCriterion("exchange_num <", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumLessThanOrEqualTo(Long value) {
			addCriterion("exchange_num <=", value, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumIn(List<Long> values) {
			addCriterion("exchange_num in", values, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumNotIn(List<Long> values) {
			addCriterion("exchange_num not in", values, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumBetween(Long value1, Long value2) {
			addCriterion("exchange_num between", value1, value2, "exchangeNum");
			return (Criteria) this;
		}

		public Criteria andExchangeNumNotBetween(Long value1, Long value2) {
			addCriterion("exchange_num not between", value1, value2,
					"exchangeNum");
			return (Criteria) this;
		}

		public Criteria andComTypeIsNull() {
			addCriterion("com_type is null");
			return (Criteria) this;
		}

		public Criteria andComTypeIsNotNull() {
			addCriterion("com_type is not null");
			return (Criteria) this;
		}

		public Criteria andComTypeEqualTo(Integer value) {
			addCriterion("com_type =", value, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeNotEqualTo(Integer value) {
			addCriterion("com_type <>", value, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeGreaterThan(Integer value) {
			addCriterion("com_type >", value, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("com_type >=", value, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeLessThan(Integer value) {
			addCriterion("com_type <", value, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeLessThanOrEqualTo(Integer value) {
			addCriterion("com_type <=", value, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeIn(List<Integer> values) {
			addCriterion("com_type in", values, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeNotIn(List<Integer> values) {
			addCriterion("com_type not in", values, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeBetween(Integer value1, Integer value2) {
			addCriterion("com_type between", value1, value2, "comType");
			return (Criteria) this;
		}

		public Criteria andComTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("com_type not between", value1, value2, "comType");
			return (Criteria) this;
		}

		public Criteria andBackup1IsNull() {
			addCriterion("backup1 is null");
			return (Criteria) this;
		}

		public Criteria andBackup1IsNotNull() {
			addCriterion("backup1 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup1EqualTo(String value) {
			addCriterion("backup1 =", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotEqualTo(String value) {
			addCriterion("backup1 <>", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1GreaterThan(String value) {
			addCriterion("backup1 >", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1GreaterThanOrEqualTo(String value) {
			addCriterion("backup1 >=", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1LessThan(String value) {
			addCriterion("backup1 <", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1LessThanOrEqualTo(String value) {
			addCriterion("backup1 <=", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1Like(String value) {
			addCriterion("backup1 like", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotLike(String value) {
			addCriterion("backup1 not like", value, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1In(List<String> values) {
			addCriterion("backup1 in", values, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotIn(List<String> values) {
			addCriterion("backup1 not in", values, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1Between(String value1, String value2) {
			addCriterion("backup1 between", value1, value2, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup1NotBetween(String value1, String value2) {
			addCriterion("backup1 not between", value1, value2, "backup1");
			return (Criteria) this;
		}

		public Criteria andBackup2IsNull() {
			addCriterion("backup2 is null");
			return (Criteria) this;
		}

		public Criteria andBackup2IsNotNull() {
			addCriterion("backup2 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup2EqualTo(String value) {
			addCriterion("backup2 =", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotEqualTo(String value) {
			addCriterion("backup2 <>", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2GreaterThan(String value) {
			addCriterion("backup2 >", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2GreaterThanOrEqualTo(String value) {
			addCriterion("backup2 >=", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2LessThan(String value) {
			addCriterion("backup2 <", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2LessThanOrEqualTo(String value) {
			addCriterion("backup2 <=", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2Like(String value) {
			addCriterion("backup2 like", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotLike(String value) {
			addCriterion("backup2 not like", value, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2In(List<String> values) {
			addCriterion("backup2 in", values, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotIn(List<String> values) {
			addCriterion("backup2 not in", values, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2Between(String value1, String value2) {
			addCriterion("backup2 between", value1, value2, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup2NotBetween(String value1, String value2) {
			addCriterion("backup2 not between", value1, value2, "backup2");
			return (Criteria) this;
		}

		public Criteria andBackup3IsNull() {
			addCriterion("backup3 is null");
			return (Criteria) this;
		}

		public Criteria andBackup3IsNotNull() {
			addCriterion("backup3 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup3EqualTo(String value) {
			addCriterion("backup3 =", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotEqualTo(String value) {
			addCriterion("backup3 <>", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3GreaterThan(String value) {
			addCriterion("backup3 >", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3GreaterThanOrEqualTo(String value) {
			addCriterion("backup3 >=", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3LessThan(String value) {
			addCriterion("backup3 <", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3LessThanOrEqualTo(String value) {
			addCriterion("backup3 <=", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3Like(String value) {
			addCriterion("backup3 like", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotLike(String value) {
			addCriterion("backup3 not like", value, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3In(List<String> values) {
			addCriterion("backup3 in", values, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotIn(List<String> values) {
			addCriterion("backup3 not in", values, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3Between(String value1, String value2) {
			addCriterion("backup3 between", value1, value2, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup3NotBetween(String value1, String value2) {
			addCriterion("backup3 not between", value1, value2, "backup3");
			return (Criteria) this;
		}

		public Criteria andBackup4IsNull() {
			addCriterion("backup4 is null");
			return (Criteria) this;
		}

		public Criteria andBackup4IsNotNull() {
			addCriterion("backup4 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup4EqualTo(String value) {
			addCriterion("backup4 =", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotEqualTo(String value) {
			addCriterion("backup4 <>", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4GreaterThan(String value) {
			addCriterion("backup4 >", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4GreaterThanOrEqualTo(String value) {
			addCriterion("backup4 >=", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4LessThan(String value) {
			addCriterion("backup4 <", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4LessThanOrEqualTo(String value) {
			addCriterion("backup4 <=", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4Like(String value) {
			addCriterion("backup4 like", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotLike(String value) {
			addCriterion("backup4 not like", value, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4In(List<String> values) {
			addCriterion("backup4 in", values, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotIn(List<String> values) {
			addCriterion("backup4 not in", values, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4Between(String value1, String value2) {
			addCriterion("backup4 between", value1, value2, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup4NotBetween(String value1, String value2) {
			addCriterion("backup4 not between", value1, value2, "backup4");
			return (Criteria) this;
		}

		public Criteria andBackup5IsNull() {
			addCriterion("backup5 is null");
			return (Criteria) this;
		}

		public Criteria andBackup5IsNotNull() {
			addCriterion("backup5 is not null");
			return (Criteria) this;
		}

		public Criteria andBackup5EqualTo(String value) {
			addCriterion("backup5 =", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotEqualTo(String value) {
			addCriterion("backup5 <>", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5GreaterThan(String value) {
			addCriterion("backup5 >", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5GreaterThanOrEqualTo(String value) {
			addCriterion("backup5 >=", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5LessThan(String value) {
			addCriterion("backup5 <", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5LessThanOrEqualTo(String value) {
			addCriterion("backup5 <=", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5Like(String value) {
			addCriterion("backup5 like", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotLike(String value) {
			addCriterion("backup5 not like", value, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5In(List<String> values) {
			addCriterion("backup5 in", values, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotIn(List<String> values) {
			addCriterion("backup5 not in", values, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5Between(String value1, String value2) {
			addCriterion("backup5 between", value1, value2, "backup5");
			return (Criteria) this;
		}

		public Criteria andBackup5NotBetween(String value1, String value2) {
			addCriterion("backup5 not between", value1, value2, "backup5");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hs_commodity_rule
     *
     * @mbggenerated do_not_delete_during_merge Thu May 21 15:19:09 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}