package com.cbice.distribute.core.db.model;

public class TAgencyRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency_role.id
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency_role.cd
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	private String cd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency_role.name
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_agency_role.remark
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency_role.id
	 * @return  the value of t_agency_role.id
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency_role.id
	 * @param id  the value for t_agency_role.id
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency_role.cd
	 * @return  the value of t_agency_role.cd
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public String getCd() {
		return cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency_role.cd
	 * @param cd  the value for t_agency_role.cd
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public void setCd(String cd) {
		this.cd = cd == null ? null : cd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency_role.name
	 * @return  the value of t_agency_role.name
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency_role.name
	 * @param name  the value for t_agency_role.name
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_agency_role.remark
	 * @return  the value of t_agency_role.remark
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_agency_role.remark
	 * @param remark  the value for t_agency_role.remark
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}