package com.cbice.distribute.core.db.model;

import java.util.Date;

public class THisFundjour {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.init_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long initDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.client_id
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.fund_account
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String fundAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.money_type
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String moneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.exchange_type
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.curr_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long currDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.curr_time
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long currTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.business_flag
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long businessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.op_branch_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long opBranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.operator_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String operatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.op_station
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String opStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.op_entrust_way
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String opEntrustWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.branch_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.bank_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.occur_balance
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long occurBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.post_balance
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long postBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.join_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.join_serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long joinSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.bk_serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String bkSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.frozen_kind
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String frozenKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.join_info
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String joinInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.remark
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.real_status
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String realStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.position_str
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String positionStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.cancel_serialno
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String cancelSerialno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.client_group
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long clientGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.room_code
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long roomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.asset_prop
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String assetProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.limit_flag
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long limitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.risk_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long riskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.corp_client_group
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long corpClientGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.corp_risk_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Long corpRiskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.asset_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String assetLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.client_name
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_his_fundjour.nature_time
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    private Date natureTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.init_date
     *
     * @return the value of t_his_fundjour.init_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getInitDate() {
        return initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.init_date
     *
     * @param initDate the value for t_his_fundjour.init_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setInitDate(Long initDate) {
        this.initDate = initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.serial_no
     *
     * @return the value of t_his_fundjour.serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.serial_no
     *
     * @param serialNo the value for t_his_fundjour.serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.client_id
     *
     * @return the value of t_his_fundjour.client_id
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.client_id
     *
     * @param clientId the value for t_his_fundjour.client_id
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.fund_account
     *
     * @return the value of t_his_fundjour.fund_account
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getFundAccount() {
        return fundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.fund_account
     *
     * @param fundAccount the value for t_his_fundjour.fund_account
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setFundAccount(String fundAccount) {
        this.fundAccount = fundAccount == null ? null : fundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.money_type
     *
     * @return the value of t_his_fundjour.money_type
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getMoneyType() {
        return moneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.money_type
     *
     * @param moneyType the value for t_his_fundjour.money_type
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setMoneyType(String moneyType) {
        this.moneyType = moneyType == null ? null : moneyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.exchange_type
     *
     * @return the value of t_his_fundjour.exchange_type
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getExchangeType() {
        return exchangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.exchange_type
     *
     * @param exchangeType the value for t_his_fundjour.exchange_type
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType == null ? null : exchangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.curr_date
     *
     * @return the value of t_his_fundjour.curr_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getCurrDate() {
        return currDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.curr_date
     *
     * @param currDate the value for t_his_fundjour.curr_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setCurrDate(Long currDate) {
        this.currDate = currDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.curr_time
     *
     * @return the value of t_his_fundjour.curr_time
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getCurrTime() {
        return currTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.curr_time
     *
     * @param currTime the value for t_his_fundjour.curr_time
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setCurrTime(Long currTime) {
        this.currTime = currTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.business_flag
     *
     * @return the value of t_his_fundjour.business_flag
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getBusinessFlag() {
        return businessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.business_flag
     *
     * @param businessFlag the value for t_his_fundjour.business_flag
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setBusinessFlag(Long businessFlag) {
        this.businessFlag = businessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.op_branch_no
     *
     * @return the value of t_his_fundjour.op_branch_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getOpBranchNo() {
        return opBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.op_branch_no
     *
     * @param opBranchNo the value for t_his_fundjour.op_branch_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setOpBranchNo(Long opBranchNo) {
        this.opBranchNo = opBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.operator_no
     *
     * @return the value of t_his_fundjour.operator_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getOperatorNo() {
        return operatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.operator_no
     *
     * @param operatorNo the value for t_his_fundjour.operator_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setOperatorNo(String operatorNo) {
        this.operatorNo = operatorNo == null ? null : operatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.op_station
     *
     * @return the value of t_his_fundjour.op_station
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getOpStation() {
        return opStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.op_station
     *
     * @param opStation the value for t_his_fundjour.op_station
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setOpStation(String opStation) {
        this.opStation = opStation == null ? null : opStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.op_entrust_way
     *
     * @return the value of t_his_fundjour.op_entrust_way
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getOpEntrustWay() {
        return opEntrustWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.op_entrust_way
     *
     * @param opEntrustWay the value for t_his_fundjour.op_entrust_way
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setOpEntrustWay(String opEntrustWay) {
        this.opEntrustWay = opEntrustWay == null ? null : opEntrustWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.branch_no
     *
     * @return the value of t_his_fundjour.branch_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.branch_no
     *
     * @param branchNo the value for t_his_fundjour.branch_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setBranchNo(Long branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.bank_no
     *
     * @return the value of t_his_fundjour.bank_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.bank_no
     *
     * @param bankNo the value for t_his_fundjour.bank_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.occur_balance
     *
     * @return the value of t_his_fundjour.occur_balance
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getOccurBalance() {
        return occurBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.occur_balance
     *
     * @param occurBalance the value for t_his_fundjour.occur_balance
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setOccurBalance(Long occurBalance) {
        this.occurBalance = occurBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.post_balance
     *
     * @return the value of t_his_fundjour.post_balance
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getPostBalance() {
        return postBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.post_balance
     *
     * @param postBalance the value for t_his_fundjour.post_balance
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setPostBalance(Long postBalance) {
        this.postBalance = postBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.join_date
     *
     * @return the value of t_his_fundjour.join_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.join_date
     *
     * @param joinDate the value for t_his_fundjour.join_date
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setJoinDate(Long joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.join_serial_no
     *
     * @return the value of t_his_fundjour.join_serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getJoinSerialNo() {
        return joinSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.join_serial_no
     *
     * @param joinSerialNo the value for t_his_fundjour.join_serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setJoinSerialNo(Long joinSerialNo) {
        this.joinSerialNo = joinSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.bk_serial_no
     *
     * @return the value of t_his_fundjour.bk_serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getBkSerialNo() {
        return bkSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.bk_serial_no
     *
     * @param bkSerialNo the value for t_his_fundjour.bk_serial_no
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setBkSerialNo(String bkSerialNo) {
        this.bkSerialNo = bkSerialNo == null ? null : bkSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.frozen_kind
     *
     * @return the value of t_his_fundjour.frozen_kind
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getFrozenKind() {
        return frozenKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.frozen_kind
     *
     * @param frozenKind the value for t_his_fundjour.frozen_kind
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setFrozenKind(String frozenKind) {
        this.frozenKind = frozenKind == null ? null : frozenKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.join_info
     *
     * @return the value of t_his_fundjour.join_info
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getJoinInfo() {
        return joinInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.join_info
     *
     * @param joinInfo the value for t_his_fundjour.join_info
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setJoinInfo(String joinInfo) {
        this.joinInfo = joinInfo == null ? null : joinInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.remark
     *
     * @return the value of t_his_fundjour.remark
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.remark
     *
     * @param remark the value for t_his_fundjour.remark
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.real_status
     *
     * @return the value of t_his_fundjour.real_status
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getRealStatus() {
        return realStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.real_status
     *
     * @param realStatus the value for t_his_fundjour.real_status
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setRealStatus(String realStatus) {
        this.realStatus = realStatus == null ? null : realStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.position_str
     *
     * @return the value of t_his_fundjour.position_str
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getPositionStr() {
        return positionStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.position_str
     *
     * @param positionStr the value for t_his_fundjour.position_str
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setPositionStr(String positionStr) {
        this.positionStr = positionStr == null ? null : positionStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.cancel_serialno
     *
     * @return the value of t_his_fundjour.cancel_serialno
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getCancelSerialno() {
        return cancelSerialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.cancel_serialno
     *
     * @param cancelSerialno the value for t_his_fundjour.cancel_serialno
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setCancelSerialno(String cancelSerialno) {
        this.cancelSerialno = cancelSerialno == null ? null : cancelSerialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.client_group
     *
     * @return the value of t_his_fundjour.client_group
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getClientGroup() {
        return clientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.client_group
     *
     * @param clientGroup the value for t_his_fundjour.client_group
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setClientGroup(Long clientGroup) {
        this.clientGroup = clientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.room_code
     *
     * @return the value of t_his_fundjour.room_code
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getRoomCode() {
        return roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.room_code
     *
     * @param roomCode the value for t_his_fundjour.room_code
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setRoomCode(Long roomCode) {
        this.roomCode = roomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.asset_prop
     *
     * @return the value of t_his_fundjour.asset_prop
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getAssetProp() {
        return assetProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.asset_prop
     *
     * @param assetProp the value for t_his_fundjour.asset_prop
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setAssetProp(String assetProp) {
        this.assetProp = assetProp == null ? null : assetProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.limit_flag
     *
     * @return the value of t_his_fundjour.limit_flag
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getLimitFlag() {
        return limitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.limit_flag
     *
     * @param limitFlag the value for t_his_fundjour.limit_flag
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setLimitFlag(Long limitFlag) {
        this.limitFlag = limitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.risk_level
     *
     * @return the value of t_his_fundjour.risk_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.risk_level
     *
     * @param riskLevel the value for t_his_fundjour.risk_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setRiskLevel(Long riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.corp_client_group
     *
     * @return the value of t_his_fundjour.corp_client_group
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getCorpClientGroup() {
        return corpClientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.corp_client_group
     *
     * @param corpClientGroup the value for t_his_fundjour.corp_client_group
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setCorpClientGroup(Long corpClientGroup) {
        this.corpClientGroup = corpClientGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.corp_risk_level
     *
     * @return the value of t_his_fundjour.corp_risk_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Long getCorpRiskLevel() {
        return corpRiskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.corp_risk_level
     *
     * @param corpRiskLevel the value for t_his_fundjour.corp_risk_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setCorpRiskLevel(Long corpRiskLevel) {
        this.corpRiskLevel = corpRiskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.asset_level
     *
     * @return the value of t_his_fundjour.asset_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getAssetLevel() {
        return assetLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.asset_level
     *
     * @param assetLevel the value for t_his_fundjour.asset_level
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setAssetLevel(String assetLevel) {
        this.assetLevel = assetLevel == null ? null : assetLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.client_name
     *
     * @return the value of t_his_fundjour.client_name
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.client_name
     *
     * @param clientName the value for t_his_fundjour.client_name
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_his_fundjour.nature_time
     *
     * @return the value of t_his_fundjour.nature_time
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public Date getNatureTime() {
        return natureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_his_fundjour.nature_time
     *
     * @param natureTime the value for t_his_fundjour.nature_time
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    public void setNatureTime(Date natureTime) {
        this.natureTime = natureTime;
    }
}