package com.cbice.distribute.core.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TOtcstockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public TOtcstockExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBranchNoIsNull() {
            addCriterion("branch_no is null");
            return (Criteria) this;
        }

        public Criteria andBranchNoIsNotNull() {
            addCriterion("branch_no is not null");
            return (Criteria) this;
        }

        public Criteria andBranchNoEqualTo(Long value) {
            addCriterion("branch_no =", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotEqualTo(Long value) {
            addCriterion("branch_no <>", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoGreaterThan(Long value) {
            addCriterion("branch_no >", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoGreaterThanOrEqualTo(Long value) {
            addCriterion("branch_no >=", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoLessThan(Long value) {
            addCriterion("branch_no <", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoLessThanOrEqualTo(Long value) {
            addCriterion("branch_no <=", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoIn(List<Long> values) {
            addCriterion("branch_no in", values, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotIn(List<Long> values) {
            addCriterion("branch_no not in", values, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoBetween(Long value1, Long value2) {
            addCriterion("branch_no between", value1, value2, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotBetween(Long value1, Long value2) {
            addCriterion("branch_no not between", value1, value2, "branchNo");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeIsNull() {
            addCriterion("otcexch_type is null");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeIsNotNull() {
            addCriterion("otcexch_type is not null");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeEqualTo(String value) {
            addCriterion("otcexch_type =", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeNotEqualTo(String value) {
            addCriterion("otcexch_type <>", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeGreaterThan(String value) {
            addCriterion("otcexch_type >", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("otcexch_type >=", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeLessThan(String value) {
            addCriterion("otcexch_type <", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeLessThanOrEqualTo(String value) {
            addCriterion("otcexch_type <=", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeLike(String value) {
            addCriterion("otcexch_type like", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeNotLike(String value) {
            addCriterion("otcexch_type not like", value, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeIn(List<String> values) {
            addCriterion("otcexch_type in", values, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeNotIn(List<String> values) {
            addCriterion("otcexch_type not in", values, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeBetween(String value1, String value2) {
            addCriterion("otcexch_type between", value1, value2, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcexchTypeNotBetween(String value1, String value2) {
            addCriterion("otcexch_type not between", value1, value2, "otcexchType");
            return (Criteria) this;
        }

        public Criteria andOtcAccountIsNull() {
            addCriterion("otc_account is null");
            return (Criteria) this;
        }

        public Criteria andOtcAccountIsNotNull() {
            addCriterion("otc_account is not null");
            return (Criteria) this;
        }

        public Criteria andOtcAccountEqualTo(String value) {
            addCriterion("otc_account =", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountNotEqualTo(String value) {
            addCriterion("otc_account <>", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountGreaterThan(String value) {
            addCriterion("otc_account >", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountGreaterThanOrEqualTo(String value) {
            addCriterion("otc_account >=", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountLessThan(String value) {
            addCriterion("otc_account <", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountLessThanOrEqualTo(String value) {
            addCriterion("otc_account <=", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountLike(String value) {
            addCriterion("otc_account like", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountNotLike(String value) {
            addCriterion("otc_account not like", value, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountIn(List<String> values) {
            addCriterion("otc_account in", values, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountNotIn(List<String> values) {
            addCriterion("otc_account not in", values, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountBetween(String value1, String value2) {
            addCriterion("otc_account between", value1, value2, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcAccountNotBetween(String value1, String value2) {
            addCriterion("otc_account not between", value1, value2, "otcAccount");
            return (Criteria) this;
        }

        public Criteria andOtcCodeIsNull() {
            addCriterion("otc_code is null");
            return (Criteria) this;
        }

        public Criteria andOtcCodeIsNotNull() {
            addCriterion("otc_code is not null");
            return (Criteria) this;
        }

        public Criteria andOtcCodeEqualTo(String value) {
            addCriterion("otc_code =", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeNotEqualTo(String value) {
            addCriterion("otc_code <>", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeGreaterThan(String value) {
            addCriterion("otc_code >", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeGreaterThanOrEqualTo(String value) {
            addCriterion("otc_code >=", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeLessThan(String value) {
            addCriterion("otc_code <", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeLessThanOrEqualTo(String value) {
            addCriterion("otc_code <=", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeLike(String value) {
            addCriterion("otc_code like", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeNotLike(String value) {
            addCriterion("otc_code not like", value, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeIn(List<String> values) {
            addCriterion("otc_code in", values, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeNotIn(List<String> values) {
            addCriterion("otc_code not in", values, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeBetween(String value1, String value2) {
            addCriterion("otc_code between", value1, value2, "otcCode");
            return (Criteria) this;
        }

        public Criteria andOtcCodeNotBetween(String value1, String value2) {
            addCriterion("otc_code not between", value1, value2, "otcCode");
            return (Criteria) this;
        }

        public Criteria andFundAccountIsNull() {
            addCriterion("fund_account is null");
            return (Criteria) this;
        }

        public Criteria andFundAccountIsNotNull() {
            addCriterion("fund_account is not null");
            return (Criteria) this;
        }

        public Criteria andFundAccountEqualTo(String value) {
            addCriterion("fund_account =", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountNotEqualTo(String value) {
            addCriterion("fund_account <>", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountGreaterThan(String value) {
            addCriterion("fund_account >", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountGreaterThanOrEqualTo(String value) {
            addCriterion("fund_account >=", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountLessThan(String value) {
            addCriterion("fund_account <", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountLessThanOrEqualTo(String value) {
            addCriterion("fund_account <=", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountLike(String value) {
            addCriterion("fund_account like", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountNotLike(String value) {
            addCriterion("fund_account not like", value, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountIn(List<String> values) {
            addCriterion("fund_account in", values, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountNotIn(List<String> values) {
            addCriterion("fund_account not in", values, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountBetween(String value1, String value2) {
            addCriterion("fund_account between", value1, value2, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andFundAccountNotBetween(String value1, String value2) {
            addCriterion("fund_account not between", value1, value2, "fundAccount");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("client_id like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("client_id not like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<String> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<String> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeIsNull() {
            addCriterion("money_type is null");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeIsNotNull() {
            addCriterion("money_type is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeEqualTo(String value) {
            addCriterion("money_type =", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeNotEqualTo(String value) {
            addCriterion("money_type <>", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeGreaterThan(String value) {
            addCriterion("money_type >", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("money_type >=", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeLessThan(String value) {
            addCriterion("money_type <", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeLessThanOrEqualTo(String value) {
            addCriterion("money_type <=", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeLike(String value) {
            addCriterion("money_type like", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeNotLike(String value) {
            addCriterion("money_type not like", value, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeIn(List<String> values) {
            addCriterion("money_type in", values, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeNotIn(List<String> values) {
            addCriterion("money_type not in", values, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeBetween(String value1, String value2) {
            addCriterion("money_type between", value1, value2, "moneyType");
            return (Criteria) this;
        }

        public Criteria andMoneyTypeNotBetween(String value1, String value2) {
            addCriterion("money_type not between", value1, value2, "moneyType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeIsNull() {
            addCriterion("otc_type is null");
            return (Criteria) this;
        }

        public Criteria andOtcTypeIsNotNull() {
            addCriterion("otc_type is not null");
            return (Criteria) this;
        }

        public Criteria andOtcTypeEqualTo(String value) {
            addCriterion("otc_type =", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeNotEqualTo(String value) {
            addCriterion("otc_type <>", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeGreaterThan(String value) {
            addCriterion("otc_type >", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("otc_type >=", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeLessThan(String value) {
            addCriterion("otc_type <", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeLessThanOrEqualTo(String value) {
            addCriterion("otc_type <=", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeLike(String value) {
            addCriterion("otc_type like", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeNotLike(String value) {
            addCriterion("otc_type not like", value, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeIn(List<String> values) {
            addCriterion("otc_type in", values, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeNotIn(List<String> values) {
            addCriterion("otc_type not in", values, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeBetween(String value1, String value2) {
            addCriterion("otc_type between", value1, value2, "otcType");
            return (Criteria) this;
        }

        public Criteria andOtcTypeNotBetween(String value1, String value2) {
            addCriterion("otc_type not between", value1, value2, "otcType");
            return (Criteria) this;
        }

        public Criteria andBeginAmountIsNull() {
            addCriterion("begin_amount is null");
            return (Criteria) this;
        }

        public Criteria andBeginAmountIsNotNull() {
            addCriterion("begin_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBeginAmountEqualTo(Long value) {
            addCriterion("begin_amount =", value, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountNotEqualTo(Long value) {
            addCriterion("begin_amount <>", value, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountGreaterThan(Long value) {
            addCriterion("begin_amount >", value, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("begin_amount >=", value, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountLessThan(Long value) {
            addCriterion("begin_amount <", value, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountLessThanOrEqualTo(Long value) {
            addCriterion("begin_amount <=", value, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountIn(List<Long> values) {
            addCriterion("begin_amount in", values, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountNotIn(List<Long> values) {
            addCriterion("begin_amount not in", values, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountBetween(Long value1, Long value2) {
            addCriterion("begin_amount between", value1, value2, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andBeginAmountNotBetween(Long value1, Long value2) {
            addCriterion("begin_amount not between", value1, value2, "beginAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountIsNull() {
            addCriterion("current_amount is null");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountIsNotNull() {
            addCriterion("current_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountEqualTo(Long value) {
            addCriterion("current_amount =", value, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountNotEqualTo(Long value) {
            addCriterion("current_amount <>", value, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountGreaterThan(Long value) {
            addCriterion("current_amount >", value, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("current_amount >=", value, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountLessThan(Long value) {
            addCriterion("current_amount <", value, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountLessThanOrEqualTo(Long value) {
            addCriterion("current_amount <=", value, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountIn(List<Long> values) {
            addCriterion("current_amount in", values, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountNotIn(List<Long> values) {
            addCriterion("current_amount not in", values, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountBetween(Long value1, Long value2) {
            addCriterion("current_amount between", value1, value2, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentAmountNotBetween(Long value1, Long value2) {
            addCriterion("current_amount not between", value1, value2, "currentAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountIsNull() {
            addCriterion("uncome_buy_amount is null");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountIsNotNull() {
            addCriterion("uncome_buy_amount is not null");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountEqualTo(Long value) {
            addCriterion("uncome_buy_amount =", value, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountNotEqualTo(Long value) {
            addCriterion("uncome_buy_amount <>", value, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountGreaterThan(Long value) {
            addCriterion("uncome_buy_amount >", value, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("uncome_buy_amount >=", value, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountLessThan(Long value) {
            addCriterion("uncome_buy_amount <", value, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountLessThanOrEqualTo(Long value) {
            addCriterion("uncome_buy_amount <=", value, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountIn(List<Long> values) {
            addCriterion("uncome_buy_amount in", values, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountNotIn(List<Long> values) {
            addCriterion("uncome_buy_amount not in", values, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountBetween(Long value1, Long value2) {
            addCriterion("uncome_buy_amount between", value1, value2, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeBuyAmountNotBetween(Long value1, Long value2) {
            addCriterion("uncome_buy_amount not between", value1, value2, "uncomeBuyAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountIsNull() {
            addCriterion("uncome_sell_amount is null");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountIsNotNull() {
            addCriterion("uncome_sell_amount is not null");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountEqualTo(Long value) {
            addCriterion("uncome_sell_amount =", value, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountNotEqualTo(Long value) {
            addCriterion("uncome_sell_amount <>", value, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountGreaterThan(Long value) {
            addCriterion("uncome_sell_amount >", value, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("uncome_sell_amount >=", value, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountLessThan(Long value) {
            addCriterion("uncome_sell_amount <", value, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountLessThanOrEqualTo(Long value) {
            addCriterion("uncome_sell_amount <=", value, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountIn(List<Long> values) {
            addCriterion("uncome_sell_amount in", values, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountNotIn(List<Long> values) {
            addCriterion("uncome_sell_amount not in", values, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountBetween(Long value1, Long value2) {
            addCriterion("uncome_sell_amount between", value1, value2, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andUncomeSellAmountNotBetween(Long value1, Long value2) {
            addCriterion("uncome_sell_amount not between", value1, value2, "uncomeSellAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountIsNull() {
            addCriterion("frozen_amount is null");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountIsNotNull() {
            addCriterion("frozen_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountEqualTo(Long value) {
            addCriterion("frozen_amount =", value, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountNotEqualTo(Long value) {
            addCriterion("frozen_amount <>", value, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountGreaterThan(Long value) {
            addCriterion("frozen_amount >", value, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("frozen_amount >=", value, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountLessThan(Long value) {
            addCriterion("frozen_amount <", value, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountLessThanOrEqualTo(Long value) {
            addCriterion("frozen_amount <=", value, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountIn(List<Long> values) {
            addCriterion("frozen_amount in", values, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountNotIn(List<Long> values) {
            addCriterion("frozen_amount not in", values, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountBetween(Long value1, Long value2) {
            addCriterion("frozen_amount between", value1, value2, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andFrozenAmountNotBetween(Long value1, Long value2) {
            addCriterion("frozen_amount not between", value1, value2, "frozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountIsNull() {
            addCriterion("unfrozen_amount is null");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountIsNotNull() {
            addCriterion("unfrozen_amount is not null");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountEqualTo(Long value) {
            addCriterion("unfrozen_amount =", value, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountNotEqualTo(Long value) {
            addCriterion("unfrozen_amount <>", value, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountGreaterThan(Long value) {
            addCriterion("unfrozen_amount >", value, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("unfrozen_amount >=", value, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountLessThan(Long value) {
            addCriterion("unfrozen_amount <", value, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountLessThanOrEqualTo(Long value) {
            addCriterion("unfrozen_amount <=", value, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountIn(List<Long> values) {
            addCriterion("unfrozen_amount in", values, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountNotIn(List<Long> values) {
            addCriterion("unfrozen_amount not in", values, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountBetween(Long value1, Long value2) {
            addCriterion("unfrozen_amount between", value1, value2, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andUnfrozenAmountNotBetween(Long value1, Long value2) {
            addCriterion("unfrozen_amount not between", value1, value2, "unfrozenAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountIsNull() {
            addCriterion("correct_amount is null");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountIsNotNull() {
            addCriterion("correct_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountEqualTo(Long value) {
            addCriterion("correct_amount =", value, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountNotEqualTo(Long value) {
            addCriterion("correct_amount <>", value, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountGreaterThan(Long value) {
            addCriterion("correct_amount >", value, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("correct_amount >=", value, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountLessThan(Long value) {
            addCriterion("correct_amount <", value, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountLessThanOrEqualTo(Long value) {
            addCriterion("correct_amount <=", value, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountIn(List<Long> values) {
            addCriterion("correct_amount in", values, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountNotIn(List<Long> values) {
            addCriterion("correct_amount not in", values, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountBetween(Long value1, Long value2) {
            addCriterion("correct_amount between", value1, value2, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andCorrectAmountNotBetween(Long value1, Long value2) {
            addCriterion("correct_amount not between", value1, value2, "correctAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountIsNull() {
            addCriterion("sum_buy_amount is null");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountIsNotNull() {
            addCriterion("sum_buy_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountEqualTo(Long value) {
            addCriterion("sum_buy_amount =", value, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountNotEqualTo(Long value) {
            addCriterion("sum_buy_amount <>", value, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountGreaterThan(Long value) {
            addCriterion("sum_buy_amount >", value, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_buy_amount >=", value, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountLessThan(Long value) {
            addCriterion("sum_buy_amount <", value, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountLessThanOrEqualTo(Long value) {
            addCriterion("sum_buy_amount <=", value, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountIn(List<Long> values) {
            addCriterion("sum_buy_amount in", values, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountNotIn(List<Long> values) {
            addCriterion("sum_buy_amount not in", values, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountBetween(Long value1, Long value2) {
            addCriterion("sum_buy_amount between", value1, value2, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyAmountNotBetween(Long value1, Long value2) {
            addCriterion("sum_buy_amount not between", value1, value2, "sumBuyAmount");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceIsNull() {
            addCriterion("sum_buy_balance is null");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceIsNotNull() {
            addCriterion("sum_buy_balance is not null");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceEqualTo(Long value) {
            addCriterion("sum_buy_balance =", value, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceNotEqualTo(Long value) {
            addCriterion("sum_buy_balance <>", value, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceGreaterThan(Long value) {
            addCriterion("sum_buy_balance >", value, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_buy_balance >=", value, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceLessThan(Long value) {
            addCriterion("sum_buy_balance <", value, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceLessThanOrEqualTo(Long value) {
            addCriterion("sum_buy_balance <=", value, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceIn(List<Long> values) {
            addCriterion("sum_buy_balance in", values, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceNotIn(List<Long> values) {
            addCriterion("sum_buy_balance not in", values, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceBetween(Long value1, Long value2) {
            addCriterion("sum_buy_balance between", value1, value2, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumBuyBalanceNotBetween(Long value1, Long value2) {
            addCriterion("sum_buy_balance not between", value1, value2, "sumBuyBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountIsNull() {
            addCriterion("sum_sell_amount is null");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountIsNotNull() {
            addCriterion("sum_sell_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountEqualTo(Long value) {
            addCriterion("sum_sell_amount =", value, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountNotEqualTo(Long value) {
            addCriterion("sum_sell_amount <>", value, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountGreaterThan(Long value) {
            addCriterion("sum_sell_amount >", value, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_sell_amount >=", value, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountLessThan(Long value) {
            addCriterion("sum_sell_amount <", value, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountLessThanOrEqualTo(Long value) {
            addCriterion("sum_sell_amount <=", value, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountIn(List<Long> values) {
            addCriterion("sum_sell_amount in", values, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountNotIn(List<Long> values) {
            addCriterion("sum_sell_amount not in", values, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountBetween(Long value1, Long value2) {
            addCriterion("sum_sell_amount between", value1, value2, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellAmountNotBetween(Long value1, Long value2) {
            addCriterion("sum_sell_amount not between", value1, value2, "sumSellAmount");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceIsNull() {
            addCriterion("sum_sell_balance is null");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceIsNotNull() {
            addCriterion("sum_sell_balance is not null");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceEqualTo(Long value) {
            addCriterion("sum_sell_balance =", value, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceNotEqualTo(Long value) {
            addCriterion("sum_sell_balance <>", value, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceGreaterThan(Long value) {
            addCriterion("sum_sell_balance >", value, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("sum_sell_balance >=", value, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceLessThan(Long value) {
            addCriterion("sum_sell_balance <", value, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceLessThanOrEqualTo(Long value) {
            addCriterion("sum_sell_balance <=", value, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceIn(List<Long> values) {
            addCriterion("sum_sell_balance in", values, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceNotIn(List<Long> values) {
            addCriterion("sum_sell_balance not in", values, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceBetween(Long value1, Long value2) {
            addCriterion("sum_sell_balance between", value1, value2, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andSumSellBalanceNotBetween(Long value1, Long value2) {
            addCriterion("sum_sell_balance not between", value1, value2, "sumSellBalance");
            return (Criteria) this;
        }

        public Criteria andCostPriceIsNull() {
            addCriterion("cost_price is null");
            return (Criteria) this;
        }

        public Criteria andCostPriceIsNotNull() {
            addCriterion("cost_price is not null");
            return (Criteria) this;
        }

        public Criteria andCostPriceEqualTo(Long value) {
            addCriterion("cost_price =", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceNotEqualTo(Long value) {
            addCriterion("cost_price <>", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceGreaterThan(Long value) {
            addCriterion("cost_price >", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("cost_price >=", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceLessThan(Long value) {
            addCriterion("cost_price <", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceLessThanOrEqualTo(Long value) {
            addCriterion("cost_price <=", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceIn(List<Long> values) {
            addCriterion("cost_price in", values, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceNotIn(List<Long> values) {
            addCriterion("cost_price not in", values, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceBetween(Long value1, Long value2) {
            addCriterion("cost_price between", value1, value2, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceNotBetween(Long value1, Long value2) {
            addCriterion("cost_price not between", value1, value2, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCheckStrIsNull() {
            addCriterion("check_str is null");
            return (Criteria) this;
        }

        public Criteria andCheckStrIsNotNull() {
            addCriterion("check_str is not null");
            return (Criteria) this;
        }

        public Criteria andCheckStrEqualTo(String value) {
            addCriterion("check_str =", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrNotEqualTo(String value) {
            addCriterion("check_str <>", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrGreaterThan(String value) {
            addCriterion("check_str >", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrGreaterThanOrEqualTo(String value) {
            addCriterion("check_str >=", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrLessThan(String value) {
            addCriterion("check_str <", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrLessThanOrEqualTo(String value) {
            addCriterion("check_str <=", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrLike(String value) {
            addCriterion("check_str like", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrNotLike(String value) {
            addCriterion("check_str not like", value, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrIn(List<String> values) {
            addCriterion("check_str in", values, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrNotIn(List<String> values) {
            addCriterion("check_str not in", values, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrBetween(String value1, String value2) {
            addCriterion("check_str between", value1, value2, "checkStr");
            return (Criteria) this;
        }

        public Criteria andCheckStrNotBetween(String value1, String value2) {
            addCriterion("check_str not between", value1, value2, "checkStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrIsNull() {
            addCriterion("position_str is null");
            return (Criteria) this;
        }

        public Criteria andPositionStrIsNotNull() {
            addCriterion("position_str is not null");
            return (Criteria) this;
        }

        public Criteria andPositionStrEqualTo(String value) {
            addCriterion("position_str =", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrNotEqualTo(String value) {
            addCriterion("position_str <>", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrGreaterThan(String value) {
            addCriterion("position_str >", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrGreaterThanOrEqualTo(String value) {
            addCriterion("position_str >=", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrLessThan(String value) {
            addCriterion("position_str <", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrLessThanOrEqualTo(String value) {
            addCriterion("position_str <=", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrLike(String value) {
            addCriterion("position_str like", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrNotLike(String value) {
            addCriterion("position_str not like", value, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrIn(List<String> values) {
            addCriterion("position_str in", values, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrNotIn(List<String> values) {
            addCriterion("position_str not in", values, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrBetween(String value1, String value2) {
            addCriterion("position_str between", value1, value2, "positionStr");
            return (Criteria) this;
        }

        public Criteria andPositionStrNotBetween(String value1, String value2) {
            addCriterion("position_str not between", value1, value2, "positionStr");
            return (Criteria) this;
        }

        public Criteria andNatureTimeIsNull() {
            addCriterion("nature_time is null");
            return (Criteria) this;
        }

        public Criteria andNatureTimeIsNotNull() {
            addCriterion("nature_time is not null");
            return (Criteria) this;
        }

        public Criteria andNatureTimeEqualTo(Date value) {
            addCriterion("nature_time =", value, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeNotEqualTo(Date value) {
            addCriterion("nature_time <>", value, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeGreaterThan(Date value) {
            addCriterion("nature_time >", value, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("nature_time >=", value, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeLessThan(Date value) {
            addCriterion("nature_time <", value, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeLessThanOrEqualTo(Date value) {
            addCriterion("nature_time <=", value, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeIn(List<Date> values) {
            addCriterion("nature_time in", values, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeNotIn(List<Date> values) {
            addCriterion("nature_time not in", values, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeBetween(Date value1, Date value2) {
            addCriterion("nature_time between", value1, value2, "natureTime");
            return (Criteria) this;
        }

        public Criteria andNatureTimeNotBetween(Date value1, Date value2) {
            addCriterion("nature_time not between", value1, value2, "natureTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_otcstock
     *
     * @mbggenerated do_not_delete_during_merge Mon May 11 11:02:11 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_otcstock
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}