package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TFundjour;
import com.cbice.distribute.core.db.model.TFundjourExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFundjourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int countByExample(TFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int deleteByExample(TFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int insert(TFundjour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int insertSelective(TFundjour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    List<TFundjour> selectByExample(TFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") TFundjour record, @Param("example") TFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int updateByExample(@Param("record") TFundjour record, @Param("example") TFundjourExample example);
}