package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsCommodityRule;
import com.cbice.distribute.core.db.model.HsCommodityRuleExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsCommodityRuleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int countByExample(HsCommodityRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int deleteByExample(HsCommodityRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int deleteByPrimaryKey(@Param("comId") Long comId,
			@Param("exchangeId") Long exchangeId, @Param("sysId") String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int insert(HsCommodityRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int insertSelective(HsCommodityRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	List<HsCommodityRule> selectByExample(HsCommodityRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	HsCommodityRule selectByPrimaryKey(@Param("comId") Long comId,
			@Param("exchangeId") Long exchangeId, @Param("sysId") String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsCommodityRule record,
			@Param("example") HsCommodityRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByExample(@Param("record") HsCommodityRule record,
			@Param("example") HsCommodityRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByPrimaryKeySelective(HsCommodityRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_rule
	 * @mbggenerated  Fri Jun 19 17:38:54 CST 2015
	 */
	int updateByPrimaryKey(HsCommodityRule record);

	List<HsCommodityRule> queryRulesById(Map<String, Object> map);

	int insertNewComdityRole(Map<String, Object> map);
	
	int updateCommodityRule(Map<String, Object> map);

}