package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsExchangeOrder;
import com.cbice.distribute.core.db.model.HsExchangeOrderExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsExchangeOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int countByExample(HsExchangeOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int deleteByExample(HsExchangeOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insert(HsExchangeOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insertSelective(HsExchangeOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	List<HsExchangeOrder> selectByExample(HsExchangeOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	HsExchangeOrder selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsExchangeOrder record,
			@Param("example") HsExchangeOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExample(@Param("record") HsExchangeOrder record,
			@Param("example") HsExchangeOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByPrimaryKeySelective(HsExchangeOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_exchange_order
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByPrimaryKey(HsExchangeOrder record);

	List<HsExchangeOrder> selectByUserId(Map<String, Object> map);

	List<HsExchangeOrder> queryExchangeOrder(Map<String, Object> map);
	int selectCountByUserId(Map<String, Object> map);

	List<HsExchangeOrder> queryExchangeOrderAndGift(Map<String, Object> map);

	List<HsExchangeOrder> selectByPrimaryKeyAndSysId(Map<String, Object> sumMap);
}