package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsTransactionRecord;
import com.cbice.distribute.core.db.model.HsTransactionRecordExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsTransactionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    int countByExample(HsTransactionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    int deleteByExample(HsTransactionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    int insert(HsTransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    int insertSelective(HsTransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    List<HsTransactionRecord> selectByExample(HsTransactionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") HsTransactionRecord record, @Param("example") HsTransactionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_transaction_record
     *
     * @mbggenerated Fri Jun 19 09:55:26 CST 2015
     */
    int updateByExample(@Param("record") HsTransactionRecord record, @Param("example") HsTransactionRecordExample example);

	List<HsTransactionRecord> queryTodayTransactionRecord(Map<String, Object> map);
}