package com.cbice.distribute.core.db.data;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cbice.distribute.core.db.model.HsAgencyGoods;
import com.cbice.distribute.core.db.model.HsAgencyGoodsExample;
import com.cbice.distribute.core.model.GoodsDetail;

public interface HsAgencyGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int countByExample(HsAgencyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int deleteByExample(HsAgencyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int deleteByPrimaryKey(@Param("agencyId") String agencyId, @Param("goodsId") String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int insert(HsAgencyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int insertSelective(HsAgencyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    List<HsAgencyGoods> selectByExample(HsAgencyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    HsAgencyGoods selectByPrimaryKey(@Param("agencyId") String agencyId, @Param("goodsId") String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") HsAgencyGoods record, @Param("example") HsAgencyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int updateByExample(@Param("record") HsAgencyGoods record, @Param("example") HsAgencyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int updateByPrimaryKeySelective(HsAgencyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_agency_goods
     *
     * @mbggenerated Wed Aug 05 16:26:09 CST 2015
     */
    int updateByPrimaryKey(HsAgencyGoods record);
    
    List<Map<String,Object>> selectGoodsListByAgencyId(Map<String,Object> map);
    
    List<GoodsDetail> selectAllGoodsListByAgencyId(Map<String,Object> map);
    
    int countGoodsByAgencyId(Map<String,Object> map);
}