package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsCommodityApproval;
import com.cbice.distribute.core.db.model.HsCommodityApprovalExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsCommodityApprovalMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int countByExample(HsCommodityApprovalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int deleteByExample(HsCommodityApprovalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insert(HsCommodityApproval record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insertSelective(HsCommodityApproval record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	List<HsCommodityApproval> selectByExample(HsCommodityApprovalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsCommodityApproval record,
			@Param("example") HsCommodityApprovalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_commodity_approval
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExample(@Param("record") HsCommodityApproval record,
			@Param("example") HsCommodityApprovalExample example);

	List<Map<String, Object>> commodityApprovalQuery(Map<String, Object> map);

	int countCommodityApprovalQuery(Map<String, Object> map);

	List<HsCommodityApproval> queryApprovalSuccess(Map<String, Object> map);

	List<HsCommodityApproval> queryApprovalSuccessEx(Map<String, Object> map);
}