package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsSystem;
import com.cbice.distribute.core.db.model.HsSystemExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsSystemMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int countByExample(HsSystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int deleteByExample(HsSystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int deleteByPrimaryKey(String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int insert(HsSystem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int insertSelective(HsSystem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	List<HsSystem> selectByExample(HsSystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	HsSystem selectByPrimaryKey(String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsSystem record,
			@Param("example") HsSystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int updateByExample(@Param("record") HsSystem record,
			@Param("example") HsSystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int updateByPrimaryKeySelective(HsSystem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_system
	 * @mbggenerated  Fri Jun 26 09:44:29 CST 2015
	 */
	int updateByPrimaryKey(HsSystem record);

	List<Map> sysRoleQueryList(Map<String, Object> map);

	int countsysRoleQueryList(Map<String, Object> map);

	HsSystem selectBySysName(String sysName);

	List<HsSystem> queryHsSystemList();

}