package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.HsUserRights;
import com.cbice.distribute.core.db.model.HsUserRightsExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HsUserRightsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int countByExample(HsUserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int deleteByExample(HsUserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insert(HsUserRights record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int insertSelective(HsUserRights record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	List<HsUserRights> selectByExample(HsUserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExampleSelective(@Param("record") HsUserRights record,
			@Param("example") HsUserRightsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hs_user_rights
	 * @mbggenerated  Fri Jun 19 13:52:36 CST 2015
	 */
	int updateByExample(@Param("record") HsUserRights record,
			@Param("example") HsUserRightsExample example);

	int updateAvailableNum(HsUserRights hsUserRights);

	List<HsUserRights> queryUserRights(Map<String, Object> map);

	long queryUserRightsCount(Map<String, Object> map);

	HsUserRights queryBySpecialRightsCode(Map<String, Object> map);
}