package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TAgencyBusiRole;
import com.cbice.distribute.core.db.model.TAgencyBusiRoleExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TAgencyBusiRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int countByExample(TAgencyBusiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int deleteByExample(TAgencyBusiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int insert(TAgencyBusiRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int insertSelective(TAgencyBusiRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	List<TAgencyBusiRole> selectByExample(TAgencyBusiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	TAgencyBusiRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TAgencyBusiRole record,
			@Param("example") TAgencyBusiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByExample(@Param("record") TAgencyBusiRole record,
			@Param("example") TAgencyBusiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByPrimaryKeySelective(TAgencyBusiRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency_busi_role
	 * @mbggenerated  Sat Mar 07 12:13:06 CST 2015
	 */
	int updateByPrimaryKey(TAgencyBusiRole record);
    
    List<TAgencyBusiRole> selectByUserId(Long userId);
    
    int countByCondition(Map<String, Object> map);
    
    List<TAgencyBusiRole> selectByCondition(Map<String, Object> map);
    
    List<TAgencyBusiRole> selectbyAgencyLevel(Integer agencyLevel);
    
    int checkAgencyRoleName(Map<String,Object> map);
}