package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TAgency;
import com.cbice.distribute.core.db.model.TAgencyExample;

import com.cbice.distribute.core.db.model.TUser;

import java.util.List;
import java.util.Map;


import org.apache.ibatis.annotations.Param;

public interface TAgencyMapper {

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int countByExample(TAgencyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int deleteByExample(TAgencyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int insert(TAgency record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int insertSelective(TAgency record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	List<TAgency> selectByExample(TAgencyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	TAgency selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TAgency record,
			@Param("example") TAgencyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int updateByExample(@Param("record") TAgency record,
			@Param("example") TAgencyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int updateByPrimaryKeySelective(TAgency record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_agency
	 * @mbggenerated  Fri Mar 20 16:52:36 CST 2015
	 */
	int updateByPrimaryKey(TAgency record);
	int countSelectAgency(TAgency record);
    List<TAgency> selectAgency(TAgency record);
    
    //查询当前登陆用户�?��经销商等�?
    int selectLevelOfAgency(long id);
    
    //根据经销商的num和name�?��经销�?
	List<TAgency> selectAgencyBydealerNumAndName(TAgency agency);
    
    int syncPreorder();
    
    TAgency  selectByAgencyNameAndAgnecyName(Map<String,Object> map);
    /**
     * 查询当前登录的下级经�?��列表
     * @param map
     */
    List<TAgency> selectLowerDealerList(Map<String, Object> map);
}