package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TConfig;
import com.cbice.distribute.core.db.model.TConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int countByExample(TConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int deleteByExample(TConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int insert(TConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int insertSelective(TConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    List<TConfig> selectByExample(TConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    TConfig selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") TConfig record, @Param("example") TConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int updateByExample(@Param("record") TConfig record, @Param("example") TConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int updateByPrimaryKeySelective(TConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Thu Mar 26 10:57:32 CST 2015
     */
    int updateByPrimaryKey(TConfig record);
}