package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.THisOtcdeliver;
import com.cbice.distribute.core.db.model.THisOtcdeliverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THisOtcdeliverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int countByExample(THisOtcdeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int deleteByExample(THisOtcdeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int insert(THisOtcdeliver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int insertSelective(THisOtcdeliver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    List<THisOtcdeliver> selectByExample(THisOtcdeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") THisOtcdeliver record, @Param("example") THisOtcdeliverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_otcdeliver
     *
     * @mbggenerated Mon May 11 11:02:11 CST 2015
     */
    int updateByExample(@Param("record") THisOtcdeliver record, @Param("example") THisOtcdeliverExample example);
}