package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.THisFundjour;
import com.cbice.distribute.core.db.model.THisFundjourExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THisFundjourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int countByExample(THisFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int deleteByExample(THisFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int insert(THisFundjour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int insertSelective(THisFundjour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    List<THisFundjour> selectByExample(THisFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") THisFundjour record, @Param("example") THisFundjourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_his_fundjour
     *
     * @mbggenerated Mon May 11 16:18:22 CST 2015
     */
    int updateByExample(@Param("record") THisFundjour record, @Param("example") THisFundjourExample example);
}