package com.cbice.distribute.core.db.data;

import com.cbice.distribute.core.db.model.TRemainderGoods;
import com.cbice.distribute.core.db.model.TRemainderGoodsExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TRemainderGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int countByExample(TRemainderGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int deleteByExample(TRemainderGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int insert(TRemainderGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int insertSelective(TRemainderGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	List<TRemainderGoods> selectByExample(TRemainderGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	TRemainderGoods selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TRemainderGoods record,
			@Param("example") TRemainderGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int updateByExample(@Param("record") TRemainderGoods record,
			@Param("example") TRemainderGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int updateByPrimaryKeySelective(TRemainderGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_remainder_goods
	 * @mbggenerated  Wed Mar 11 20:48:34 CST 2015
	 */
	int updateByPrimaryKey(TRemainderGoods record);

	List<TRemainderGoods> selectbuyUserid(Map<String,Object> map);

	int updateNumByUserAndGoods(Map<String, Object> map);
	
	TRemainderGoods selectbuyUseridAndGoodsid(Map<String, Object> map);
	
	List<Map<String, Object>> selectRemainderGoodsApplcation(Map<String, Object> map);
	int selectRemainderGoodsApplcationCount(Map<String, Object> map);
	String selectAgencyId(@Param(value="user_id")Long user_id);
	
	List<Map<String, Object>> selectLowRemainderGoodsApplcation(Map<String, Object> map);
	int selectLowRemainderGoodsApplcationCount(Map<String, Object> map);
	
	TRemainderGoods selecyBuyCondition(Map<String,Object> map);
	int updateTRemainderGoodsByUserIdAndGoodId(TRemainderGoods tRemainderGoods);
}